import json
import random

# Common word types and their Turkish meanings
word_data = {
    "nouns": [
        ("ability", "yetenek"), ("access", "erişim"), ("account", "hesap"), ("action", "eylem"),
        ("activity", "aktivite"), ("address", "adres"), ("adult", "yetişkin"), ("advantage", "avantaj"),
        ("advertisement", "reklam"), ("advice", "tavsiye"), ("age", "yaş"), ("agency", "ajans"),
        ("agent", "ajan"), ("agreement", "anlaşma"), ("air", "hava"), ("airport", "havaalanı"),
        ("alarm", "alarm"), ("album", "albüm"), ("alcohol", "alkol"), ("ambition", "hırs"),
        ("amount", "miktar"), ("anger", "öfke"), ("animal", "hayvan"), ("answer", "cevap"),
        ("apartment", "daire"), ("appearance", "görünüm"), ("apple", "elma"), ("application", "uygulama"),
        ("area", "alan"), ("arm", "kol"), ("army", "ordu"), ("art", "sanat"), ("article", "makale"),
        ("artist", "sanatçı"), ("aspect", "görünüm"), ("assignment", "görev"), ("assistant", "asistan"),
        ("atmosphere", "atmosfer"), ("attention", "dikkat"), ("attitude", "tavır"), ("audience", "izleyici"),
        ("author", "yazar"), ("authority", "yetki"), ("background", "arka plan"), ("bag", "çanta"),
        ("balance", "denge"), ("ball", "top"), ("bank", "banka"), ("bar", "bar"), ("base", "temel"),
        ("battle", "savaş"), ("beach", "sahil"), ("beauty", "güzellik"), ("bed", "yatak"), ("beginning", "başlangıç"),
        ("behavior", "davranış"), ("belief", "inanç"), ("benefit", "fayda"), ("bird", "kuş"), ("birth", "doğum"),
        ("blood", "kan"), ("board", "tahta"), ("boat", "tekne"), ("body", "vücut"), ("book", "kitap"),
        ("border", "sınır"), ("boss", "patron"), ("bottom", "alt"), ("box", "kutu"), ("boy", "erkek çocuk"),
        ("brain", "beyin"), ("branch", "dal"), ("bread", "ekmek"), ("break", "mola"), ("breakfast", "kahvaltı"),
        ("breath", "nefes"), ("bridge", "köprü"), ("brother", "erkek kardeş"), ("building", "bina"),
        ("business", "iş"), ("camera", "kamera"), ("car", "araba"), ("card", "kart"), ("care", "bakım"),
        ("career", "kariyer"), ("case", "durum"), ("cash", "nakit"), ("cat", "kedi"), ("cause", "sebep"),
        ("cell", "hücre"), ("center", "merkez"), ("chair", "sandalye"), ("challenge", "meydan okuma"),
        ("chance", "şans"), ("change", "değişiklik"), ("character", "karakter"), ("charge", "ücret"),
        ("check", "kontrol"), ("child", "çocuk"), ("choice", "seçim"), ("church", "kilise"), ("city", "şehir"),
        ("class", "sınıf"), ("client", "müşteri"), ("climate", "iklim"), ("clothes", "kıyafet"), ("cloud", "bulut"),
        ("coffee", "kahve"), ("college", "kolej"), ("color", "renk"), ("comfort", "konfor"), ("company", "şirket"),
        ("computer", "bilgisayar"), ("concept", "kavram"), ("condition", "durum"), ("confidence", "güven"),
        ("connection", "bağlantı"), ("consequence", "sonuç"), ("construction", "inşaat"), ("contact", "iletişim"),
        ("content", "içerik"), ("context", "bağlam"), ("control", "kontrol"), ("conversation", "konuşma"),
        ("country", "ülke"), ("course", "kurs"), ("court", "mahkeme"), ("cover", "kapak"), ("culture", "kültür"),
        ("customer", "müşteri"), ("danger", "tehlike"), ("data", "veri"), ("daughter", "kız"), ("day", "gün"),
        ("death", "ölüm"), ("decision", "karar"), ("degree", "derece"), ("demand", "talep"), ("design", "tasarım"),
        ("desire", "arzu"), ("development", "gelişim"), ("difference", "fark"), ("difficulty", "zorluk"),
        ("dinner", "akşam yemeği"), ("direction", "yön"), ("disease", "hastalık"), ("doctor", "doktor"),
        ("dog", "köpek"), ("door", "kapı"), ("dream", "rüya"), ("driver", "sürücü"), ("earth", "dünya"),
        ("education", "eğitim"), ("effect", "etki"), ("effort", "çaba"), ("energy", "enerji"), ("engine", "motor"),
        ("environment", "çevre"), ("equipment", "ekipman"), ("example", "örnek"), ("experience", "deneyim"),
        ("expert", "uzman"), ("fact", "gerçek"), ("family", "aile"), ("father", "baba"), ("fear", "korku"),
        ("feeling", "duygu"), ("field", "alan"), ("figure", "figür"), ("film", "film"), ("fire", "ateş"),
        ("fish", "balık"), ("food", "yiyecek"), ("force", "güç"), ("friend", "arkadaş"), ("future", "gelecek"),
        ("game", "oyun"), ("garden", "bahçe"), ("gas", "gaz"), ("girl", "kız"), ("goal", "hedef"),
        ("government", "hükümet"), ("group", "grup"), ("growth", "büyüme"), ("hair", "saç"), ("hand", "el"),
        ("head", "baş"), ("health", "sağlık"), ("heart", "kalp"), ("heat", "ısı"), ("help", "yardım"),
        ("history", "tarih"), ("home", "ev"), ("hope", "umut"), ("hour", "saat"), ("house", "ev"),
        ("idea", "fikir"), ("image", "görüntü"), ("importance", "önem"), ("industry", "endüstri"), ("information", "bilgi"),
        ("interest", "ilgi"), ("issue", "sorun"), ("job", "iş"), ("knowledge", "bilgi"), ("language", "dil"),
        ("law", "yasa"), ("level", "seviye"), ("life", "yaşam"), ("light", "ışık"), ("line", "çizgi"),
        ("list", "liste"), ("love", "aşk"), ("machine", "makine"), ("man", "adam"), ("market", "pazar"),
        ("material", "malzeme"), ("matter", "madde"), ("meeting", "toplantı"), ("method", "yöntem"), ("mind", "akıl"),
        ("money", "para"), ("month", "ay"), ("morning", "sabah"), ("mother", "anne"), ("music", "müzik"),
        ("name", "isim"), ("nature", "doğa"), ("night", "gece"), ("number", "sayı"), ("office", "ofis"),
        ("oil", "yağ"), ("opinion", "görüş"), ("order", "sipariş"), ("paper", "kağıt"), ("party", "parti"),
        ("people", "insanlar"), ("person", "kişi"), ("picture", "resim"), ("place", "yer"), ("plan", "plan"),
        ("point", "nokta"), ("power", "güç"), ("problem", "problem"), ("product", "ürün"), ("program", "program"),
        ("question", "soru"), ("reason", "sebep"), ("result", "sonuç"), ("road", "yol"), ("room", "oda"),
        ("school", "okul"), ("science", "bilim"), ("service", "hizmet"), ("side", "yan"), ("society", "toplum"),
        ("space", "boşluk"), ("story", "hikaye"), ("student", "öğrenci"), ("study", "çalışma"), ("system", "sistem"),
        ("table", "masa"), ("teacher", "öğretmen"), ("team", "takım"), ("technology", "teknoloji"), ("thing", "şey"),
        ("time", "zaman"), ("today", "bugün"), ("town", "kasaba"), ("tree", "ağaç"), ("water", "su"),
        ("way", "yol"), ("week", "hafta"), ("woman", "kadın"), ("word", "kelime"), ("work", "iş"),
        ("world", "dünya"), ("year", "yıl"), ("ability", "yetenek"), ("access", "erişim"), ("account", "hesap"),
        ("action", "eylem"), ("activity", "aktivite"), ("address", "adres"), ("adult", "yetişkin"), ("advantage", "avantaj"),
        ("advertisement", "reklam"), ("advice", "tavsiye"), ("age", "yaş"), ("agency", "ajans"), ("agent", "ajan"),
        ("agreement", "anlaşma"), ("air", "hava"), ("airport", "havaalanı"), ("alarm", "alarm"), ("album", "albüm"),
        ("alcohol", "alkol"), ("ambition", "hırs"), ("amount", "miktar"), ("anger", "öfke"), ("animal", "hayvan"),
        ("answer", "cevap"), ("apartment", "daire"), ("appearance", "görünüm"), ("apple", "elma"), ("application", "uygulama"),
        ("area", "alan"), ("arm", "kol"), ("army", "ordu"), ("art", "sanat"), ("article", "makale"), ("artist", "sanatçı"),
        ("aspect", "görünüm"), ("assignment", "görev"), ("assistant", "asistan"), ("atmosphere", "atmosfer"),
        ("attention", "dikkat"), ("attitude", "tavır"), ("audience", "izleyici"), ("author", "yazar"), ("authority", "yetki"),
        ("background", "arka plan"), ("bag", "çanta"), ("balance", "denge"), ("ball", "top"), ("bank", "banka"),
        ("bar", "bar"), ("base", "temel"), ("battle", "savaş"), ("beach", "sahil"), ("beauty", "güzellik"),
        ("bed", "yatak"), ("beginning", "başlangıç"), ("behavior", "davranış"), ("belief", "inanç"), ("benefit", "fayda"),
        ("bird", "kuş"), ("birth", "doğum"), ("blood", "kan"), ("board", "tahta"), ("boat", "tekne"), ("body", "vücut"),
        ("book", "kitap"), ("border", "sınır"), ("boss", "patron"), ("bottom", "alt"), ("box", "kutu"), ("boy", "erkek çocuk"),
        ("brain", "beyin"), ("branch", "dal"), ("bread", "ekmek"), ("break", "mola"), ("breakfast", "kahvaltı"),
        ("breath", "nefes"), ("bridge", "köprü"), ("brother", "erkek kardeş"), ("building", "bina"), ("business", "iş"),
        ("camera", "kamera"), ("car", "araba"), ("card", "kart"), ("care", "bakım"), ("career", "kariyer"), ("case", "durum"),
        ("cash", "nakit"), ("cat", "kedi"), ("cause", "sebep"), ("cell", "hücre"), ("center", "merkez"), ("chair", "sandalye"),
        ("challenge", "meydan okuma"), ("chance", "şans"), ("change", "değişiklik"), ("character", "karakter"), ("charge", "ücret"),
        ("check", "kontrol"), ("child", "çocuk"), ("choice", "seçim"), ("church", "kilise"), ("city", "şehir"), ("class", "sınıf"),
        ("client", "müşteri"), ("climate", "iklim"), ("clothes", "kıyafet"), ("cloud", "bulut"), ("coffee", "kahve"),
        ("college", "kolej"), ("color", "renk"), ("comfort", "konfor"), ("company", "şirket"), ("computer", "bilgisayar"),
        ("concept", "kavram"), ("condition", "durum"), ("confidence", "güven"), ("connection", "bağlantı"), ("consequence", "sonuç"),
        ("construction", "inşaat"), ("contact", "iletişim"), ("content", "içerik"), ("context", "bağlam"), ("control", "kontrol"),
        ("conversation", "konuşma"), ("country", "ülke"), ("course", "kurs"), ("court", "mahkeme"), ("cover", "kapak"),
        ("culture", "kültür"), ("customer", "müşteri"), ("danger", "tehlike"), ("data", "veri"), ("daughter", "kız"), ("day", "gün"),
        ("death", "ölüm"), ("decision", "karar"), ("degree", "derece"), ("demand", "talep"), ("design", "tasarım"), ("desire", "arzu"),
        ("development", "gelişim"), ("difference", "fark"), ("difficulty", "zorluk"), ("dinner", "akşam yemeği"), ("direction", "yön"),
        ("disease", "hastalık"), ("doctor", "doktor"), ("dog", "köpek"), ("door", "kapı"), ("dream", "rüya"), ("driver", "sürücü"),
        ("earth", "dünya"), ("education", "eğitim"), ("effect", "etki"), ("effort", "çaba"), ("energy", "enerji"), ("engine", "motor"),
        ("environment", "çevre"), ("equipment", "ekipman"), ("example", "örnek"), ("experience", "deneyim"), ("expert", "uzman"),
        ("fact", "gerçek"), ("family", "aile"), ("father", "baba"), ("fear", "korku"), ("feeling", "duygu"), ("field", "alan"),
        ("figure", "figür"), ("film", "film"), ("fire", "ateş"), ("fish", "balık"), ("food", "yiyecek"), ("force", "güç"),
        ("friend", "arkadaş"), ("future", "gelecek"), ("game", "oyun"), ("garden", "bahçe"), ("gas", "gaz"), ("girl", "kız"),
        ("goal", "hedef"), ("government", "hükümet"), ("group", "grup"), ("growth", "büyüme"), ("hair", "saç"), ("hand", "el"),
        ("head", "baş"), ("health", "sağlık"), ("heart", "kalp"), ("heat", "ısı"), ("help", "yardım"), ("history", "tarih"),
        ("home", "ev"), ("hope", "umut"), ("hour", "saat"), ("house", "ev"), ("idea", "fikir"), ("image", "görüntü"),
        ("importance", "önem"), ("industry", "endüstri"), ("information", "bilgi"), ("interest", "ilgi"), ("issue", "sorun"),
        ("job", "iş"), ("knowledge", "bilgi"), ("language", "dil"), ("law", "yasa"), ("level", "seviye"), ("life", "yaşam"),
        ("light", "ışık"), ("line", "çizgi"), ("list", "liste"), ("love", "aşk"), ("machine", "makine"), ("man", "adam"),
        ("market", "pazar"), ("material", "malzeme"), ("matter", "madde"), ("meeting", "toplantı"), ("method", "yöntem"),
        ("mind", "akıl"), ("money", "para"), ("month", "ay"), ("morning", "sabah"), ("mother", "anne"), ("music", "müzik"),
        ("name", "isim"), ("nature", "doğa"), ("night", "gece"), ("number", "sayı"), ("office", "ofis"), ("oil", "yağ"),
        ("opinion", "görüş"), ("order", "sipariş"), ("paper", "kağıt"), ("party", "parti"), ("people", "insanlar"),
        ("person", "kişi"), ("picture", "resim"), ("place", "yer"), ("plan", "plan"), ("point", "nokta"), ("power", "güç"),
        ("problem", "problem"), ("product", "ürün"), ("program", "program"), ("question", "soru"), ("reason", "sebep"),
        ("result", "sonuç"), ("road", "yol"), ("room", "oda"), ("school", "okul"), ("science", "bilim"), ("service", "hizmet"),
        ("side", "yan"), ("society", "toplum"), ("space", "boşluk"), ("story", "hikaye"), ("student", "öğrenci"), ("study", "çalışma"),
        ("system", "sistem"), ("table", "masa"), ("teacher", "öğretmen"), ("team", "takım"), ("technology", "teknoloji"),
        ("thing", "şey"), ("time", "zaman"), ("today", "bugün"), ("town", "kasaba"), ("tree", "ağaç"), ("water", "su"),
        ("way", "yol"), ("week", "hafta"), ("woman", "kadın"), ("word", "kelime"), ("work", "iş"), ("world", "dünya"), ("year", "yıl")
    ],
    "verbs": [
        ("accept", "kabul etmek"), ("achieve", "elde etmek"), ("act", "hareket etmek"), ("add", "eklemek"),
        ("admit", "kabul etmek"), ("advance", "ilerlemek"), ("agree", "katılmak"), ("allow", "izin vermek"),
        ("answer", "cevaplamak"), ("appear", "görünmek"), ("apply", "başvurmak"), ("argue", "tartışmak"),
        ("arrive", "varmak"), ("ask", "sormak"), ("avoid", "kaçınmak"), ("become", "olmak"), ("begin", "başlamak"),
        ("believe", "inanmak"), ("bring", "getirmek"), ("build", "inşa etmek"), ("buy", "satın almak"),
        ("call", "aramak"), ("carry", "taşımak"), ("catch", "yakalamak"), ("change", "değiştirmek"),
        ("choose", "seçmek"), ("come", "gelmek"), ("consider", "düşünmek"), ("continue", "devam etmek"),
        ("create", "yaratmak"), ("cut", "kesmek"), ("decide", "karar vermek"), ("develop", "geliştirmek"),
        ("die", "ölmek"), ("do", "yapmak"), ("draw", "çizmek"), ("drive", "sürmek"), ("eat", "yemek"),
        ("end", "bitirmek"), ("expect", "beklemek"), ("explain", "açıklamak"), ("fall", "düşmek"),
        ("feel", "hissetmek"), ("find", "bulmak"), ("finish", "bitirmek"), ("follow", "takip etmek"),
        ("forget", "unutmak"), ("get", "almak"), ("give", "vermek"), ("go", "gitmek"), ("grow", "büyümek"),
        ("happen", "olmak"), ("have", "sahip olmak"), ("hear", "duymak"), ("help", "yardım etmek"),
        ("hold", "tutmak"), ("hope", "umut etmek"), ("include", "dahil etmek"), ("increase", "artırmak"),
        ("indicate", "göstermek"), ("join", "katılmak"), ("keep", "tutmak"), ("know", "bilmek"),
        ("learn", "öğrenmek"), ("leave", "ayrılmak"), ("let", "izin vermek"), ("like", "beğenmek"),
        ("live", "yaşamak"), ("look", "bakmak"), ("love", "sevmek"), ("make", "yapmak"), ("mean", "anlamına gelmek"),
        ("meet", "buluşmak"), ("move", "hareket etmek"), ("need", "ihtiyaç duymak"), ("open", "açmak"),
        ("pay", "ödemek"), ("play", "oynamak"), ("provide", "sağlamak"), ("put", "koymak"), ("read", "okumak"),
        ("receive", "almak"), ("remember", "hatırlamak"), ("report", "rapor etmek"), ("require", "gerektirmek"),
        ("return", "dönmek"), ("run", "koşmak"), ("say", "söylemek"), ("see", "görmek"), ("seem", "görünmek"),
        ("send", "göndermek"), ("serve", "hizmet vermek"), ("set", "ayarlamak"), ("show", "göstermek"),
        ("sit", "oturmak"), ("speak", "konuşmak"), ("spend", "harcamak"), ("stand", "durmak"), ("start", "başlamak"),
        ("stay", "kalmak"), ("stop", "durmak"), ("take", "almak"), ("talk", "konuşmak"), ("tell", "söylemek"),
        ("think", "düşünmek"), ("try", "denemek"), ("turn", "dönmek"), ("understand", "anlamak"), ("use", "kullanmak"),
        ("walk", "yürümek"), ("want", "istemek"), ("watch", "izlemek"), ("work", "çalışmak"), ("write", "yazmak"),
        ("accept", "kabul etmek"), ("achieve", "elde etmek"), ("act", "hareket etmek"), ("add", "eklemek"),
        ("admit", "kabul etmek"), ("advance", "ilerlemek"), ("agree", "katılmak"), ("allow", "izin vermek"),
        ("answer", "cevaplamak"), ("appear", "görünmek"), ("apply", "başvurmak"), ("argue", "tartışmak"),
        ("arrive", "varmak"), ("ask", "sormak"), ("avoid", "kaçınmak"), ("become", "olmak"), ("begin", "başlamak"),
        ("believe", "inanmak"), ("bring", "getirmek"), ("build", "inşa etmek"), ("buy", "satın almak"),
        ("call", "aramak"), ("carry", "taşımak"), ("catch", "yakalamak"), ("change", "değiştirmek"),
        ("choose", "seçmek"), ("come", "gelmek"), ("consider", "düşünmek"), ("continue", "devam etmek"),
        ("create", "yaratmak"), ("cut", "kesmek"), ("decide", "karar vermek"), ("develop", "geliştirmek"),
        ("die", "ölmek"), ("do", "yapmak"), ("draw", "çizmek"), ("drive", "sürmek"), ("eat", "yemek"),
        ("end", "bitirmek"), ("expect", "beklemek"), ("explain", "açıklamak"), ("fall", "düşmek"),
        ("feel", "hissetmek"), ("find", "bulmak"), ("finish", "bitirmek"), ("follow", "takip etmek"),
        ("forget", "unutmak"), ("get", "almak"), ("give", "vermek"), ("go", "gitmek"), ("grow", "büyümek"),
        ("happen", "olmak"), ("have", "sahip olmak"), ("hear", "duymak"), ("help", "yardım etmek"),
        ("hold", "tutmak"), ("hope", "umut etmek"), ("include", "dahil etmek"), ("increase", "artırmak"),
        ("indicate", "göstermek"), ("join", "katılmak"), ("keep", "tutmak"), ("know", "bilmek"),
        ("learn", "öğrenmek"), ("leave", "ayrılmak"), ("let", "izin vermek"), ("like", "beğenmek"),
        ("live", "yaşamak"), ("look", "bakmak"), ("love", "sevmek"), ("make", "yapmak"), ("mean", "anlamına gelmek"),
        ("meet", "buluşmak"), ("move", "hareket etmek"), ("need", "ihtiyaç duymak"), ("open", "açmak"),
        ("pay", "ödemek"), ("play", "oynamak"), ("provide", "sağlamak"), ("put", "koymak"), ("read", "okumak"),
        ("receive", "almak"), ("remember", "hatırlamak"), ("report", "rapor etmek"), ("require", "gerektirmek"),
        ("return", "dönmek"), ("run", "koşmak"), ("say", "söylemek"), ("see", "görmek"), ("seem", "görünmek"),
        ("send", "göndermek"), ("serve", "hizmet vermek"), ("set", "ayarlamak"), ("show", "göstermek"),
        ("sit", "oturmak"), ("speak", "konuşmak"), ("spend", "harcamak"), ("stand", "durmak"), ("start", "başlamak"),
        ("stay", "kalmak"), ("stop", "durmak"), ("take", "almak"), ("talk", "konuşmak"), ("tell", "söylemek"),
        ("think", "düşünmek"), ("try", "denemek"), ("turn", "dönmek"), ("understand", "anlamak"), ("use", "kullanmak"),
        ("walk", "yürümek"), ("want", "istemek"), ("watch", "izlemek"), ("work", "çalışmak"), ("write", "yazmak")
    ],
    "adjectives": [
        ("able", "yapabilir"), ("active", "aktif"), ("actual", "gerçek"), ("afraid", "korkmuş"),
        ("alive", "canlı"), ("alone", "yalnız"), ("angry", "kızgın"), ("another", "başka"), ("anxious", "endişeli"),
        ("available", "mevcut"), ("bad", "kötü"), ("beautiful", "güzel"), ("big", "büyük"), ("black", "siyah"),
        ("blue", "mavi"), ("boring", "sıkıcı"), ("brave", "cesur"), ("bright", "parlak"), ("brown", "kahverengi"),
        ("busy", "meşgul"), ("calm", "sakin"), ("careful", "dikkatli"), ("cheap", "ucuz"), ("clean", "temiz"),
        ("clear", "açık"), ("close", "yakın"), ("cold", "soğuk"), ("comfortable", "rahat"), ("common", "yaygın"),
        ("complete", "tam"), ("correct", "doğru"), ("crazy", "deli"), ("dangerous", "tehlikeli"), ("dark", "karanlık"),
        ("dead", "ölü"), ("deep", "derin"), ("different", "farklı"), ("difficult", "zor"), ("dirty", "kirli"),
        ("dry", "kuru"), ("early", "erken"), ("easy", "kolay"), ("empty", "boş"), ("enough", "yeterli"),
        ("excellent", "mükemmel"), ("expensive", "pahalı"), ("fair", "adil"), ("famous", "ünlü"), ("far", "uzak"),
        ("fast", "hızlı"), ("fat", "şişman"), ("fine", "iyi"), ("first", "ilk"), ("free", "ücretsiz"),
        ("fresh", "taze"), ("friendly", "arkadaşça"), ("full", "dolu"), ("funny", "komik"), ("good", "iyi"),
        ("great", "harika"), ("green", "yeşil"), ("happy", "mutlu"), ("hard", "sert"), ("healthy", "sağlıklı"),
        ("heavy", "ağır"), ("high", "yüksek"), ("hot", "sıcak"), ("huge", "dev"), ("hungry", "aç"),
        ("important", "önemli"), ("impossible", "imkansız"), ("interesting", "ilginç"), ("large", "büyük"),
        ("late", "geç"), ("lazy", "tembel"), ("light", "hafif"), ("little", "küçük"), ("long", "uzun"),
        ("loud", "yüksek sesli"), ("low", "düşük"), ("lucky", "şanslı"), ("main", "ana"), ("modern", "modern"),
        ("much", "çok"), ("natural", "doğal"), ("necessary", "gerekli"), ("new", "yeni"), ("nice", "güzel"),
        ("normal", "normal"), ("old", "eski"), ("only", "sadece"), ("open", "açık"), ("other", "diğer"),
        ("perfect", "mükemmel"), ("personal", "kişisel"), ("poor", "fakir"), ("popular", "popüler"), ("possible", "mümkün"),
        ("powerful", "güçlü"), ("pretty", "güzel"), ("private", "özel"), ("public", "genel"), ("quick", "hızlı"),
        ("quiet", "sessiz"), ("ready", "hazır"), ("real", "gerçek"), ("red", "kırmızı"), ("rich", "zengin"),
        ("right", "doğru"), ("sad", "üzgün"), ("safe", "güvenli"), ("same", "aynı"), ("serious", "ciddi"),
        ("short", "kısa"), ("simple", "basit"), ("small", "küçük"), ("soft", "yumuşak"), ("special", "özel"),
        ("strong", "güçlü"), ("stupid", "aptal"), ("sure", "emin"), ("sweet", "tatlı"), ("tall", "uzun"),
        ("terrible", "korkunç"), ("thick", "kalın"), ("thin", "ince"), ("tired", "yorulmuş"), ("true", "doğru"),
        ("ugly", "çirkin"), ("useful", "faydalı"), ("warm", "sıcak"), ("weak", "zayıf"), ("white", "beyaz"),
        ("whole", "tüm"), ("wide", "geniş"), ("wild", "vahşi"), ("wonderful", "harika"), ("wrong", "yanlış"),
        ("yellow", "sarı"), ("young", "genç"), ("able", "yapabilir"), ("active", "aktif"), ("actual", "gerçek"),
        ("afraid", "korkmuş"), ("alive", "canlı"), ("alone", "yalnız"), ("angry", "kızgın"), ("another", "başka"),
        ("anxious", "endişeli"), ("available", "mevcut"), ("bad", "kötü"), ("beautiful", "güzel"), ("big", "büyük"),
        ("black", "siyah"), ("blue", "mavi"), ("boring", "sıkıcı"), ("brave", "cesur"), ("bright", "parlak"),
        ("brown", "kahverengi"), ("busy", "meşgul"), ("calm", "sakin"), ("careful", "dikkatli"), ("cheap", "ucuz"),
        ("clean", "temiz"), ("clear", "açık"), ("close", "yakın"), ("cold", "soğuk"), ("comfortable", "rahat"),
        ("common", "yaygın"), ("complete", "tam"), ("correct", "doğru"), ("crazy", "deli"), ("dangerous", "tehlikeli"),
        ("dark", "karanlık"), ("dead", "ölü"), ("deep", "derin"), ("different", "farklı"), ("difficult", "zor"),
        ("dirty", "kirli"), ("dry", "kuru"), ("early", "erken"), ("easy", "kolay"), ("empty", "boş"), ("enough", "yeterli"),
        ("excellent", "mükemmel"), ("expensive", "pahalı"), ("fair", "adil"), ("famous", "ünlü"), ("far", "uzak"),
        ("fast", "hızlı"), ("fat", "şişman"), ("fine", "iyi"), ("first", "ilk"), ("free", "ücretsiz"), ("fresh", "taze"),
        ("friendly", "arkadaşça"), ("full", "dolu"), ("funny", "komik"), ("good", "iyi"), ("great", "harika"),
        ("green", "yeşil"), ("happy", "mutlu"), ("hard", "sert"), ("healthy", "sağlıklı"), ("heavy", "ağır"),
        ("high", "yüksek"), ("hot", "sıcak"), ("huge", "dev"), ("hungry", "aç"), ("important", "önemli"),
        ("impossible", "imkansız"), ("interesting", "ilginç"), ("large", "büyük"), ("late", "geç"), ("lazy", "tembel"),
        ("light", "hafif"), ("little", "küçük"), ("long", "uzun"), ("loud", "yüksek sesli"), ("low", "düşük"),
        ("lucky", "şanslı"), ("main", "ana"), ("modern", "modern"), ("much", "çok"), ("natural", "doğal"),
        ("necessary", "gerekli"), ("new", "yeni"), ("nice", "güzel"), ("normal", "normal"), ("old", "eski"),
        ("only", "sadece"), ("open", "açık"), ("other", "diğer"), ("perfect", "mükemmel"), ("personal", "kişisel"),
        ("poor", "fakir"), ("popular", "popüler"), ("possible", "mümkün"), ("powerful", "güçlü"), ("pretty", "güzel"),
        ("private", "özel"), ("public", "genel"), ("quick", "hızlı"), ("quiet", "sessiz"), ("ready", "hazır"),
        ("real", "gerçek"), ("red", "kırmızı"), ("rich", "zengin"), ("right", "doğru"), ("sad", "üzgün"),
        ("safe", "güvenli"), ("same", "aynı"), ("serious", "ciddi"), ("short", "kısa"), ("simple", "basit"),
        ("small", "küçük"), ("soft", "yumuşak"), ("special", "özel"), ("strong", "güçlü"), ("stupid", "aptal"),
        ("sure", "emin"), ("sweet", "tatlı"), ("tall", "uzun"), ("terrible", "korkunç"), ("thick", "kalın"),
        ("thin", "ince"), ("tired", "yorulmuş"), ("true", "doğru"), ("ugly", "çirkin"), ("useful", "faydalı"),
        ("warm", "sıcak"), ("weak", "zayıf"), ("white", "beyaz"), ("whole", "tüm"), ("wide", "geniş"),
        ("wild", "vahşi"), ("wonderful", "harika"), ("wrong", "yanlış"), ("yellow", "sarı"), ("young", "genç")
    ]
}

# Sample sentences for different word types
sample_sentences = {
    "nouns": [
        ("The ability to learn quickly is important.", "Hızlı öğrenme yeteneği önemlidir."),
        ("I need access to the internet.", "İnternete erişime ihtiyacım var."),
        ("She opened a bank account.", "Bir banka hesabı açtı."),
        ("The action was necessary.", "Eylem gerekliydi."),
        ("Swimming is a great activity.", "Yüzme harika bir aktivitedir."),
        ("What is your home address?", "Ev adresin nedir?"),
        ("Children need adult supervision.", "Çocukların yetişkin gözetimine ihtiyacı var."),
        ("Being tall is an advantage in basketball.", "Basketbolda uzun olmak bir avantajdır."),
        ("The advertisement was very effective.", "Reklam çok etkiliydi."),
        ("I need your advice.", "Tavsiyene ihtiyacım var.")
    ],
    "verbs": [
        ("I accept your offer.", "Teklifini kabul ediyorum."),
        ("She achieved her goal.", "Hedefini başardı."),
        ("He acted quickly.", "Hızlı hareket etti."),
        ("Please add some salt.", "Lütfen biraz tuz ekle."),
        ("I admit I was wrong.", "Yanıldığımı kabul ediyorum."),
        ("Technology continues to advance rapidly.", "Teknoloji hızla ilerlemeye devam ediyor."),
        ("I agree with you.", "Sana katılıyorum."),
        ("The teacher allowed us to leave early.", "Öğretmen erken ayrılmamıza izin verdi."),
        ("Can you answer this question?", "Bu soruyu cevaplayabilir misin?"),
        ("She appeared suddenly.", "Aniden göründü.")
    ],
    "adjectives": [
        ("She is able to help.", "Yardım edebilir."),
        ("He leads an active lifestyle.", "Aktif bir yaşam tarzı sürüyor."),
        ("The actual cost was higher.", "Gerçek maliyet daha yüksekti."),
        ("Don't be afraid.", "Korkma."),
        ("The plant is still alive.", "Bitki hala canlı."),
        ("I feel alone.", "Yalnız hissediyorum."),
        ("Why are you angry?", "Neden kızgınsın?"),
        ("I need another chance.", "Başka bir şansa ihtiyacım var."),
        ("She looks anxious.", "Endişeli görünüyor."),
        ("The book is available in the library.", "Kitap kütüphanede mevcut.")
    ]
}

def generate_words():
    words = []
    word_count = 0
    
    # Generate words from each category
    for word_type, word_list in word_data.items():
        for word, meaning in word_list:
            if word_count >= 3000:
                break
                
            # Get sample sentences for this word type
            sentences = sample_sentences[word_type]
            sentence_en, sentence_tr = random.choice(sentences)
            
            # Create word entry
            word_entry = {
                "word": word,
                "type": word_type[:-1],  # Remove 's' from end
                "meaning": meaning,
                "sentence_en": sentence_en,
                "sentence_tr": sentence_tr
            }
            
            words.append(word_entry)
            word_count += 1
    
    return words

# Generate 3000 words
all_words = generate_words()

# Save to JSON file
with open('public/words.json', 'w', encoding='utf-8') as f:
    json.dump(all_words, f, ensure_ascii=False, indent=2)

print(f"Created {len(all_words)} words in words.json") 