import json
import random

# Mevcut kelimeleri oku
with open('public/words.json', 'r', encoding='utf-8') as f:
    existing_words = json.load(f)

print(f"Mevcut kelime sayısı: {len(existing_words)}")

# Daha fazla kelime ekleyelim
additional_words = [
    # Daha fazla Adjectives
    {"word": "accurate", "type": "adjective", "meaning": "doğru, kesin", "sentence_en": "The weather forecast was accurate.", "sentence_tr": "Hava tahmini doğruydu."},
    {"word": "active", "type": "adjective", "meaning": "aktif", "sentence_en": "She leads a very active lifestyle.", "sentence_tr": "Çok aktif bir yaşam tarzı sürüyor."},
    {"word": "advanced", "type": "adjective", "meaning": "ileri, gelişmiş", "sentence_en": "This is an advanced course.", "sentence_tr": "Bu ileri bir kurs."},
    {"word": "amazing", "type": "adjective", "meaning": "şaşırtıcı", "sentence_en": "The view was amazing.", "sentence_tr": "Manzara şaşırtıcıydı."},
    {"word": "ancient", "type": "adjective", "meaning": "eski, antik", "sentence_en": "They found ancient ruins.", "sentence_tr": "Eski kalıntılar buldular."},
    {"word": "appropriate", "type": "adjective", "meaning": "uygun", "sentence_en": "This is not appropriate behavior.", "sentence_tr": "Bu uygun bir davranış değil."},
    {"word": "artificial", "type": "adjective", "meaning": "yapay", "sentence_en": "This is artificial intelligence.", "sentence_tr": "Bu yapay zeka."},
    {"word": "automatic", "type": "adjective", "meaning": "otomatik", "sentence_en": "The door is automatic.", "sentence_tr": "Kapı otomatik."},
    {"word": "available", "type": "adjective", "meaning": "mevcut", "sentence_en": "The product is available now.", "sentence_tr": "Ürün şimdi mevcut."},
    {"word": "average", "type": "adjective", "meaning": "ortalama", "sentence_en": "His grades are average.", "sentence_tr": "Notları ortalama."},
    {"word": "basic", "type": "adjective", "meaning": "temel", "sentence_en": "These are basic skills.", "sentence_tr": "Bunlar temel beceriler."},
    {"word": "beautiful", "type": "adjective", "meaning": "güzel", "sentence_en": "She is beautiful.", "sentence_tr": "O güzel."},
    {"word": "big", "type": "adjective", "meaning": "büyük", "sentence_en": "This is a big house.", "sentence_tr": "Bu büyük bir ev."},
    {"word": "bright", "type": "adjective", "meaning": "parlak", "sentence_en": "The sun is bright.", "sentence_tr": "Güneş parlak."},
    {"word": "busy", "type": "adjective", "meaning": "meşgul", "sentence_en": "I am busy today.", "sentence_tr": "Bugün meşgulüm."},
    {"word": "calm", "type": "adjective", "meaning": "sakin", "sentence_en": "The sea is calm.", "sentence_tr": "Deniz sakin."},
    {"word": "careful", "type": "adjective", "meaning": "dikkatli", "sentence_en": "Be careful!", "sentence_tr": "Dikkatli ol!"},
    {"word": "central", "type": "adjective", "meaning": "merkezi", "sentence_en": "This is the central station.", "sentence_tr": "Bu merkez istasyon."},
    {"word": "certain", "type": "adjective", "meaning": "kesin", "sentence_en": "I am certain about this.", "sentence_tr": "Bu konuda kesinim."},
    {"word": "cheap", "type": "adjective", "meaning": "ucuz", "sentence_en": "This is cheap.", "sentence_tr": "Bu ucuz."},
    {"word": "clean", "type": "adjective", "meaning": "temiz", "sentence_en": "The room is clean.", "sentence_tr": "Oda temiz."},
    {"word": "clear", "type": "adjective", "meaning": "açık", "sentence_en": "The sky is clear.", "sentence_tr": "Gökyüzü açık."},
    {"word": "close", "type": "adjective", "meaning": "yakın", "sentence_en": "The store is close.", "sentence_tr": "Mağaza yakın."},
    {"word": "cold", "type": "adjective", "meaning": "soğuk", "sentence_en": "The weather is cold.", "sentence_tr": "Hava soğuk."},
    {"word": "common", "type": "adjective", "meaning": "yaygın", "sentence_en": "This is a common problem.", "sentence_tr": "Bu yaygın bir problem."},
    {"word": "complete", "type": "adjective", "meaning": "tam", "sentence_en": "The work is complete.", "sentence_tr": "İş tamamlandı."},
    {"word": "complex", "type": "adjective", "meaning": "karmaşık", "sentence_en": "This is complex.", "sentence_tr": "Bu karmaşık."},
    {"word": "constant", "type": "adjective", "meaning": "sürekli", "sentence_en": "There is constant noise.", "sentence_tr": "Sürekli gürültü var."},
    {"word": "correct", "type": "adjective", "meaning": "doğru", "sentence_en": "This answer is correct.", "sentence_tr": "Bu cevap doğru."},
    {"word": "current", "type": "adjective", "meaning": "güncel", "sentence_en": "This is current news.", "sentence_tr": "Bu güncel haber."},
    {"word": "dangerous", "type": "adjective", "meaning": "tehlikeli", "sentence_en": "This is dangerous.", "sentence_tr": "Bu tehlikeli."},
    {"word": "dark", "type": "adjective", "meaning": "karanlık", "sentence_en": "The room is dark.", "sentence_tr": "Oda karanlık."},
    {"word": "deep", "type": "adjective", "meaning": "derin", "sentence_en": "The water is deep.", "sentence_tr": "Su derin."},
    {"word": "different", "type": "adjective", "meaning": "farklı", "sentence_en": "This is different.", "sentence_tr": "Bu farklı."},
    {"word": "difficult", "type": "adjective", "meaning": "zor", "sentence_en": "This is difficult.", "sentence_tr": "Bu zor."},
    {"word": "direct", "type": "adjective", "meaning": "doğrudan", "sentence_en": "This is the direct way.", "sentence_tr": "Bu doğrudan yol."},
    {"word": "dirty", "type": "adjective", "meaning": "kirli", "sentence_en": "The clothes are dirty.", "sentence_tr": "Kıyafetler kirli."},
    {"word": "dry", "type": "adjective", "meaning": "kuru", "sentence_en": "The air is dry.", "sentence_tr": "Hava kuru."},
    {"word": "easy", "type": "adjective", "meaning": "kolay", "sentence_en": "This is easy.", "sentence_tr": "Bu kolay."},
    {"word": "empty", "type": "adjective", "meaning": "boş", "sentence_en": "The bottle is empty.", "sentence_tr": "Şişe boş."},
    {"word": "equal", "type": "adjective", "meaning": "eşit", "sentence_en": "They are equal.", "sentence_tr": "Onlar eşit."},
    {"word": "exact", "type": "adjective", "meaning": "tam", "sentence_en": "This is the exact time.", "sentence_tr": "Bu tam zaman."},
    {"word": "expensive", "type": "adjective", "meaning": "pahalı", "sentence_en": "This is expensive.", "sentence_tr": "Bu pahalı."},
    {"word": "external", "type": "adjective", "meaning": "dış", "sentence_en": "This is external.", "sentence_tr": "Bu dış."},
    {"word": "fair", "type": "adjective", "meaning": "adil", "sentence_en": "This is fair.", "sentence_tr": "Bu adil."},
    {"word": "false", "type": "adjective", "meaning": "yanlış", "sentence_en": "This is false.", "sentence_tr": "Bu yanlış."},
    {"word": "famous", "type": "adjective", "meaning": "ünlü", "sentence_en": "She is famous.", "sentence_tr": "O ünlü."},
    {"word": "fast", "type": "adjective", "meaning": "hızlı", "sentence_en": "He is fast.", "sentence_tr": "O hızlı."},
    {"word": "fat", "type": "adjective", "meaning": "şişman", "sentence_en": "The cat is fat.", "sentence_tr": "Kedi şişman."},
    {"word": "final", "type": "adjective", "meaning": "son", "sentence_en": "This is the final decision.", "sentence_tr": "Bu son karar."},
    {"word": "fine", "type": "adjective", "meaning": "iyi", "sentence_en": "I am fine.", "sentence_tr": "İyiyim."},
    {"word": "flat", "type": "adjective", "meaning": "düz", "sentence_en": "The surface is flat.", "sentence_tr": "Yüzey düz."},
    {"word": "foreign", "type": "adjective", "meaning": "yabancı", "sentence_en": "This is foreign.", "sentence_tr": "Bu yabancı."},
    {"word": "free", "type": "adjective", "meaning": "ücretsiz", "sentence_en": "This is free.", "sentence_tr": "Bu ücretsiz."},
    {"word": "fresh", "type": "adjective", "meaning": "taze", "sentence_en": "The bread is fresh.", "sentence_tr": "Ekmek taze."},
    {"word": "full", "type": "adjective", "meaning": "dolu", "sentence_en": "The glass is full.", "sentence_tr": "Bardak dolu."},
    {"word": "funny", "type": "adjective", "meaning": "komik", "sentence_en": "This is funny.", "sentence_tr": "Bu komik."},
    {"word": "future", "type": "adjective", "meaning": "gelecek", "sentence_en": "This is the future.", "sentence_tr": "Bu gelecek."},
    {"word": "general", "type": "adjective", "meaning": "genel", "sentence_en": "This is general knowledge.", "sentence_tr": "Bu genel bilgi."},
    {"word": "good", "type": "adjective", "meaning": "iyi", "sentence_en": "This is good.", "sentence_tr": "Bu iyi."},
    {"word": "great", "type": "adjective", "meaning": "harika", "sentence_en": "This is great.", "sentence_tr": "Bu harika."},
    {"word": "green", "type": "adjective", "meaning": "yeşil", "sentence_en": "The grass is green.", "sentence_tr": "Çimen yeşil."},
    {"word": "happy", "type": "adjective", "meaning": "mutlu", "sentence_en": "I am happy.", "sentence_tr": "Mutluyum."},
    {"word": "hard", "type": "adjective", "meaning": "sert", "sentence_en": "This is hard.", "sentence_tr": "Bu sert."},
    {"word": "heavy", "type": "adjective", "meaning": "ağır", "sentence_en": "This is heavy.", "sentence_tr": "Bu ağır."},
    {"word": "high", "type": "adjective", "meaning": "yüksek", "sentence_en": "The mountain is high.", "sentence_tr": "Dağ yüksek."},
    {"word": "hot", "type": "adjective", "meaning": "sıcak", "sentence_en": "The coffee is hot.", "sentence_tr": "Kahve sıcak."},
    {"word": "huge", "type": "adjective", "meaning": "dev", "sentence_en": "This is huge.", "sentence_tr": "Bu dev."},
    {"word": "human", "type": "adjective", "meaning": "insan", "sentence_en": "This is human nature.", "sentence_tr": "Bu insan doğası."},
    {"word": "immediate", "type": "adjective", "meaning": "acil", "sentence_en": "This needs immediate attention.", "sentence_tr": "Bu acil dikkat gerektiriyor."},
    {"word": "important", "type": "adjective", "meaning": "önemli", "sentence_en": "This is important.", "sentence_tr": "Bu önemli."},
    {"word": "impossible", "type": "adjective", "meaning": "imkansız", "sentence_en": "This is impossible.", "sentence_tr": "Bu imkansız."},
    {"word": "independent", "type": "adjective", "meaning": "bağımsız", "sentence_en": "She is independent.", "sentence_tr": "O bağımsız."},
    {"word": "individual", "type": "adjective", "meaning": "bireysel", "sentence_en": "This is individual.", "sentence_tr": "Bu bireysel."},
    {"word": "industrial", "type": "adjective", "meaning": "endüstriyel", "sentence_en": "This is industrial.", "sentence_tr": "Bu endüstriyel."},
    {"word": "inexpensive", "type": "adjective", "meaning": "ucuz", "sentence_en": "This is inexpensive.", "sentence_tr": "Bu ucuz."},
    {"word": "international", "type": "adjective", "meaning": "uluslararası", "sentence_en": "This is international.", "sentence_tr": "Bu uluslararası."},
    {"word": "large", "type": "adjective", "meaning": "büyük", "sentence_en": "This is large.", "sentence_tr": "Bu büyük."},
    {"word": "late", "type": "adjective", "meaning": "geç", "sentence_en": "It is late.", "sentence_tr": "Geç."},
    {"word": "legal", "type": "adjective", "meaning": "yasal", "sentence_en": "This is legal.", "sentence_tr": "Bu yasal."},
    {"word": "light", "type": "adjective", "meaning": "hafif", "sentence_en": "This is light.", "sentence_tr": "Bu hafif."},
    {"word": "local", "type": "adjective", "meaning": "yerel", "sentence_en": "This is local.", "sentence_tr": "Bu yerel."},
    {"word": "long", "type": "adjective", "meaning": "uzun", "sentence_en": "This is long.", "sentence_tr": "Bu uzun."},
    {"word": "low", "type": "adjective", "meaning": "düşük", "sentence_en": "The price is low.", "sentence_tr": "Fiyat düşük."},
    {"word": "main", "type": "adjective", "meaning": "ana", "sentence_en": "This is the main road.", "sentence_tr": "Bu ana yol."},
    {"word": "major", "type": "adjective", "meaning": "büyük", "sentence_en": "This is a major problem.", "sentence_tr": "Bu büyük bir problem."},
    {"word": "medical", "type": "adjective", "meaning": "tıbbi", "sentence_en": "This is medical equipment.", "sentence_tr": "Bu tıbbi ekipman."},
    {"word": "mental", "type": "adjective", "meaning": "zihinsel", "sentence_en": "This is mental health.", "sentence_tr": "Bu zihinsel sağlık."},
    {"word": "minor", "type": "adjective", "meaning": "küçük", "sentence_en": "This is a minor issue.", "sentence_tr": "Bu küçük bir sorun."},
    {"word": "modern", "type": "adjective", "meaning": "modern", "sentence_en": "This is modern technology.", "sentence_tr": "Bu modern teknoloji."},
    {"word": "natural", "type": "adjective", "meaning": "doğal", "sentence_en": "This is natural.", "sentence_tr": "Bu doğal."},
    {"word": "necessary", "type": "adjective", "meaning": "gerekli", "sentence_en": "This is necessary.", "sentence_tr": "Bu gerekli."},
    {"word": "new", "type": "adjective", "meaning": "yeni", "sentence_en": "This is new.", "sentence_tr": "Bu yeni."},
    {"word": "normal", "type": "adjective", "meaning": "normal", "sentence_en": "This is normal.", "sentence_tr": "Bu normal."},
    {"word": "official", "type": "adjective", "meaning": "resmi", "sentence_en": "This is official.", "sentence_tr": "Bu resmi."},
    {"word": "old", "type": "adjective", "meaning": "eski", "sentence_en": "This is old.", "sentence_tr": "Bu eski."},
    {"word": "open", "type": "adjective", "meaning": "açık", "sentence_en": "The door is open.", "sentence_tr": "Kapı açık."},
    {"word": "original", "type": "adjective", "meaning": "orijinal", "sentence_en": "This is original.", "sentence_tr": "Bu orijinal."},
    {"word": "personal", "type": "adjective", "meaning": "kişisel", "sentence_en": "This is personal.", "sentence_tr": "Bu kişisel."},
    {"word": "physical", "type": "adjective", "meaning": "fiziksel", "sentence_en": "This is physical exercise.", "sentence_tr": "Bu fiziksel egzersiz."},
    {"word": "political", "type": "adjective", "meaning": "siyasi", "sentence_en": "This is political.", "sentence_tr": "Bu siyasi."},
    {"word": "poor", "type": "adjective", "meaning": "fakir", "sentence_en": "He is poor.", "sentence_tr": "O fakir."},
    {"word": "popular", "type": "adjective", "meaning": "popüler", "sentence_en": "This is popular.", "sentence_tr": "Bu popüler."},
    {"word": "positive", "type": "adjective", "meaning": "pozitif", "sentence_en": "This is positive.", "sentence_tr": "Bu pozitif."},
    {"word": "possible", "type": "adjective", "meaning": "mümkün", "sentence_en": "This is possible.", "sentence_tr": "Bu mümkün."},
    {"word": "powerful", "type": "adjective", "meaning": "güçlü", "sentence_en": "This is powerful.", "sentence_tr": "Bu güçlü."},
    {"word": "practical", "type": "adjective", "meaning": "pratik", "sentence_en": "This is practical.", "sentence_tr": "Bu pratik."},
    {"word": "private", "type": "adjective", "meaning": "özel", "sentence_en": "This is private.", "sentence_tr": "Bu özel."},
    {"word": "professional", "type": "adjective", "meaning": "profesyonel", "sentence_en": "This is professional.", "sentence_tr": "Bu profesyonel."},
    {"word": "public", "type": "adjective", "meaning": "halka açık", "sentence_en": "This is public.", "sentence_tr": "Bu halka açık."},
    {"word": "quick", "type": "adjective", "meaning": "hızlı", "sentence_en": "This is quick.", "sentence_tr": "Bu hızlı."},
    {"word": "quiet", "type": "adjective", "meaning": "sessiz", "sentence_en": "This is quiet.", "sentence_tr": "Bu sessiz."},
    {"word": "ready", "type": "adjective", "meaning": "hazır", "sentence_en": "I am ready.", "sentence_tr": "Hazırım."},
    {"word": "real", "type": "adjective", "meaning": "gerçek", "sentence_en": "This is real.", "sentence_tr": "Bu gerçek."},
    {"word": "recent", "type": "adjective", "meaning": "son", "sentence_en": "This is recent.", "sentence_tr": "Bu son."},
    {"word": "red", "type": "adjective", "meaning": "kırmızı", "sentence_en": "The apple is red.", "sentence_tr": "Elma kırmızı."},
    {"word": "regular", "type": "adjective", "meaning": "düzenli", "sentence_en": "This is regular.", "sentence_tr": "Bu düzenli."},
    {"word": "rich", "type": "adjective", "meaning": "zengin", "sentence_en": "He is rich.", "sentence_tr": "O zengin."},
    {"word": "right", "type": "adjective", "meaning": "doğru", "sentence_en": "This is right.", "sentence_tr": "Bu doğru."},
    {"word": "round", "type": "adjective", "meaning": "yuvarlak", "sentence_en": "The ball is round.", "sentence_tr": "Top yuvarlak."},
    {"word": "safe", "type": "adjective", "meaning": "güvenli", "sentence_en": "This is safe.", "sentence_tr": "Bu güvenli."},
    {"word": "same", "type": "adjective", "meaning": "aynı", "sentence_en": "This is the same.", "sentence_tr": "Bu aynı."},
    {"word": "serious", "type": "adjective", "meaning": "ciddi", "sentence_en": "This is serious.", "sentence_tr": "Bu ciddi."},
    {"word": "short", "type": "adjective", "meaning": "kısa", "sentence_en": "This is short.", "sentence_tr": "Bu kısa."},
    {"word": "simple", "type": "adjective", "meaning": "basit", "sentence_en": "This is simple.", "sentence_tr": "Bu basit."},
    {"word": "small", "type": "adjective", "meaning": "küçük", "sentence_en": "This is small.", "sentence_tr": "Bu küçük."},
    {"word": "soft", "type": "adjective", "meaning": "yumuşak", "sentence_en": "This is soft.", "sentence_tr": "Bu yumuşak."},
    {"word": "special", "type": "adjective", "meaning": "özel", "sentence_en": "This is special.", "sentence_tr": "Bu özel."},
    {"word": "strong", "type": "adjective", "meaning": "güçlü", "sentence_en": "This is strong.", "sentence_tr": "Bu güçlü."},
    {"word": "sure", "type": "adjective", "meaning": "emin", "sentence_en": "I am sure.", "sentence_tr": "Eminim."},
    {"word": "sweet", "type": "adjective", "meaning": "tatlı", "sentence_en": "This is sweet.", "sentence_tr": "Bu tatlı."},
    {"word": "tall", "type": "adjective", "meaning": "uzun", "sentence_en": "He is tall.", "sentence_tr": "O uzun."},
    {"word": "thick", "type": "adjective", "meaning": "kalın", "sentence_en": "This is thick.", "sentence_tr": "Bu kalın."},
    {"word": "thin", "type": "adjective", "meaning": "ince", "sentence_en": "This is thin.", "sentence_tr": "Bu ince."},
    {"word": "tired", "type": "adjective", "meaning": "yorgun", "sentence_en": "I am tired.", "sentence_tr": "Yorgunum."},
    {"word": "true", "type": "adjective", "meaning": "doğru", "sentence_en": "This is true.", "sentence_tr": "Bu doğru."},
    {"word": "useful", "type": "adjective", "meaning": "faydalı", "sentence_en": "This is useful.", "sentence_tr": "Bu faydalı."},
    {"word": "warm", "type": "adjective", "meaning": "ılık", "sentence_en": "The water is warm.", "sentence_tr": "Su ılık."},
    {"word": "weak", "type": "adjective", "meaning": "zayıf", "sentence_en": "This is weak.", "sentence_tr": "Bu zayıf."},
    {"word": "white", "type": "adjective", "meaning": "beyaz", "sentence_en": "The snow is white.", "sentence_tr": "Kar beyaz."},
    {"word": "wide", "type": "adjective", "meaning": "geniş", "sentence_en": "The road is wide.", "sentence_tr": "Yol geniş."},
    {"word": "wild", "type": "adjective", "meaning": "vahşi", "sentence_en": "This is wild.", "sentence_tr": "Bu vahşi."},
    {"word": "wrong", "type": "adjective", "meaning": "yanlış", "sentence_en": "This is wrong.", "sentence_tr": "Bu yanlış."},
    {"word": "yellow", "type": "adjective", "meaning": "sarı", "sentence_en": "The sun is yellow.", "sentence_tr": "Güneş sarı."},
    {"word": "young", "type": "adjective", "meaning": "genç", "sentence_en": "She is young.", "sentence_tr": "O genç."}
]

# Tüm kelimeleri birleştir
all_words = existing_words + additional_words

# Dosyaya yaz
with open('public/words.json', 'w', encoding='utf-8') as f:
    json.dump(all_words, f, ensure_ascii=False, indent=2)

print(f"Toplam {len(all_words)} kelime oluşturuldu!")
print("Dosya: public/words.json") 