import json
import random

# Mevcut kelimeleri oku
with open('public/words.json', 'r', encoding='utf-8') as f:
    existing_words = json.load(f)

print(f"Mevcut kelime sayısı: {len(existing_words)}")

# Daha fazla kelime ekleyelim (3000'e yakın olacak şekilde)
additional_words = [
    # Daha fazla Adjectives
    {"word": "absolute", "type": "adjective", "meaning": "mutlak", "sentence_en": "This is absolute truth.", "sentence_tr": "Bu mutlak gerçek."},
    {"word": "abstract", "type": "adjective", "meaning": "soyut", "sentence_en": "This is abstract art.", "sentence_tr": "Bu soyut sanat."},
    {"word": "academic", "type": "adjective", "meaning": "akademik", "sentence_en": "This is academic research.", "sentence_tr": "Bu akademik araştırma."},
    {"word": "active", "type": "adjective", "meaning": "aktif", "sentence_en": "She leads an active life.", "sentence_tr": "Aktif bir yaşam sürüyor."},
    {"word": "actual", "type": "adjective", "meaning": "gerçek", "sentence_en": "This is the actual cost.", "sentence_tr": "Bu gerçek maliyet."},
    {"word": "additional", "type": "adjective", "meaning": "ek", "sentence_en": "We need additional help.", "sentence_tr": "Ek yardıma ihtiyacımız var."},
    {"word": "adequate", "type": "adjective", "meaning": "yeterli", "sentence_en": "This is adequate.", "sentence_tr": "Bu yeterli."},
    {"word": "administrative", "type": "adjective", "meaning": "idari", "sentence_en": "This is administrative work.", "sentence_tr": "Bu idari iş."},
    {"word": "adult", "type": "adjective", "meaning": "yetişkin", "sentence_en": "This is adult content.", "sentence_tr": "Bu yetişkin içerik."},
    {"word": "advanced", "type": "adjective", "meaning": "ileri", "sentence_en": "This is advanced technology.", "sentence_tr": "Bu ileri teknoloji."},
    {"word": "adverse", "type": "adjective", "meaning": "olumsuz", "sentence_en": "This has adverse effects.", "sentence_tr": "Bunun olumsuz etkileri var."},
    {"word": "affordable", "type": "adjective", "meaning": "uygun fiyatlı", "sentence_en": "This is affordable.", "sentence_tr": "Bu uygun fiyatlı."},
    {"word": "aggressive", "type": "adjective", "meaning": "agresif", "sentence_en": "He is aggressive.", "sentence_tr": "O agresif."},
    {"word": "agricultural", "type": "adjective", "meaning": "tarımsal", "sentence_en": "This is agricultural land.", "sentence_tr": "Bu tarımsal arazi."},
    {"word": "alive", "type": "adjective", "meaning": "canlı", "sentence_en": "The plant is alive.", "sentence_tr": "Bitki canlı."},
    {"word": "alone", "type": "adjective", "meaning": "yalnız", "sentence_en": "I am alone.", "sentence_tr": "Yalnızım."},
    {"word": "amazing", "type": "adjective", "meaning": "şaşırtıcı", "sentence_en": "This is amazing.", "sentence_tr": "Bu şaşırtıcı."},
    {"word": "ancient", "type": "adjective", "meaning": "antik", "sentence_en": "This is ancient history.", "sentence_tr": "Bu antik tarih."},
    {"word": "annual", "type": "adjective", "meaning": "yıllık", "sentence_en": "This is an annual event.", "sentence_tr": "Bu yıllık bir etkinlik."},
    {"word": "anonymous", "type": "adjective", "meaning": "anonim", "sentence_en": "This is anonymous.", "sentence_tr": "Bu anonim."},
    {"word": "appropriate", "type": "adjective", "meaning": "uygun", "sentence_en": "This is appropriate.", "sentence_tr": "Bu uygun."},
    {"word": "artificial", "type": "adjective", "meaning": "yapay", "sentence_en": "This is artificial.", "sentence_tr": "Bu yapay."},
    {"word": "automatic", "type": "adjective", "meaning": "otomatik", "sentence_en": "This is automatic.", "sentence_tr": "Bu otomatik."},
    {"word": "available", "type": "adjective", "meaning": "mevcut", "sentence_en": "This is available.", "sentence_tr": "Bu mevcut."},
    {"word": "average", "type": "adjective", "meaning": "ortalama", "sentence_en": "This is average.", "sentence_tr": "Bu ortalama."},
    {"word": "basic", "type": "adjective", "meaning": "temel", "sentence_en": "This is basic.", "sentence_tr": "Bu temel."},
    {"word": "beautiful", "type": "adjective", "meaning": "güzel", "sentence_en": "She is beautiful.", "sentence_tr": "O güzel."},
    {"word": "big", "type": "adjective", "meaning": "büyük", "sentence_en": "This is big.", "sentence_tr": "Bu büyük."},
    {"word": "bright", "type": "adjective", "meaning": "parlak", "sentence_en": "This is bright.", "sentence_tr": "Bu parlak."},
    {"word": "busy", "type": "adjective", "meaning": "meşgul", "sentence_en": "I am busy.", "sentence_tr": "Meşgulüm."},
    {"word": "calm", "type": "adjective", "meaning": "sakin", "sentence_en": "This is calm.", "sentence_tr": "Bu sakin."},
    {"word": "careful", "type": "adjective", "meaning": "dikkatli", "sentence_en": "Be careful.", "sentence_tr": "Dikkatli ol."},
    {"word": "central", "type": "adjective", "meaning": "merkezi", "sentence_en": "This is central.", "sentence_tr": "Bu merkezi."},
    {"word": "certain", "type": "adjective", "meaning": "kesin", "sentence_en": "This is certain.", "sentence_tr": "Bu kesin."},
    {"word": "cheap", "type": "adjective", "meaning": "ucuz", "sentence_en": "This is cheap.", "sentence_tr": "Bu ucuz."},
    {"word": "clean", "type": "adjective", "meaning": "temiz", "sentence_en": "This is clean.", "sentence_tr": "Bu temiz."},
    {"word": "clear", "type": "adjective", "meaning": "açık", "sentence_en": "This is clear.", "sentence_tr": "Bu açık."},
    {"word": "close", "type": "adjective", "meaning": "yakın", "sentence_en": "This is close.", "sentence_tr": "Bu yakın."},
    {"word": "cold", "type": "adjective", "meaning": "soğuk", "sentence_en": "This is cold.", "sentence_tr": "Bu soğuk."},
    {"word": "common", "type": "adjective", "meaning": "yaygın", "sentence_en": "This is common.", "sentence_tr": "Bu yaygın."},
    {"word": "complete", "type": "adjective", "meaning": "tam", "sentence_en": "This is complete.", "sentence_tr": "Bu tam."},
    {"word": "complex", "type": "adjective", "meaning": "karmaşık", "sentence_en": "This is complex.", "sentence_tr": "Bu karmaşık."},
    {"word": "constant", "type": "adjective", "meaning": "sürekli", "sentence_en": "This is constant.", "sentence_tr": "Bu sürekli."},
    {"word": "correct", "type": "adjective", "meaning": "doğru", "sentence_en": "This is correct.", "sentence_tr": "Bu doğru."},
    {"word": "current", "type": "adjective", "meaning": "güncel", "sentence_en": "This is current.", "sentence_tr": "Bu güncel."},
    {"word": "dangerous", "type": "adjective", "meaning": "tehlikeli", "sentence_en": "This is dangerous.", "sentence_tr": "Bu tehlikeli."},
    {"word": "dark", "type": "adjective", "meaning": "karanlık", "sentence_en": "This is dark.", "sentence_tr": "Bu karanlık."},
    {"word": "deep", "type": "adjective", "meaning": "derin", "sentence_en": "This is deep.", "sentence_tr": "Bu derin."},
    {"word": "different", "type": "adjective", "meaning": "farklı", "sentence_en": "This is different.", "sentence_tr": "Bu farklı."},
    {"word": "difficult", "type": "adjective", "meaning": "zor", "sentence_en": "This is difficult.", "sentence_tr": "Bu zor."},
    {"word": "direct", "type": "adjective", "meaning": "doğrudan", "sentence_en": "This is direct.", "sentence_tr": "Bu doğrudan."},
    {"word": "dirty", "type": "adjective", "meaning": "kirli", "sentence_en": "This is dirty.", "sentence_tr": "Bu kirli."},
    {"word": "dry", "type": "adjective", "meaning": "kuru", "sentence_en": "This is dry.", "sentence_tr": "Bu kuru."},
    {"word": "easy", "type": "adjective", "meaning": "kolay", "sentence_en": "This is easy.", "sentence_tr": "Bu kolay."},
    {"word": "empty", "type": "adjective", "meaning": "boş", "sentence_en": "This is empty.", "sentence_tr": "Bu boş."},
    {"word": "equal", "type": "adjective", "meaning": "eşit", "sentence_en": "This is equal.", "sentence_tr": "Bu eşit."},
    {"word": "exact", "type": "adjective", "meaning": "tam", "sentence_en": "This is exact.", "sentence_tr": "Bu tam."},
    {"word": "expensive", "type": "adjective", "meaning": "pahalı", "sentence_en": "This is expensive.", "sentence_tr": "Bu pahalı."},
    {"word": "external", "type": "adjective", "meaning": "dış", "sentence_en": "This is external.", "sentence_tr": "Bu dış."},
    {"word": "fair", "type": "adjective", "meaning": "adil", "sentence_en": "This is fair.", "sentence_tr": "Bu adil."},
    {"word": "false", "type": "adjective", "meaning": "yanlış", "sentence_en": "This is false.", "sentence_tr": "Bu yanlış."},
    {"word": "famous", "type": "adjective", "meaning": "ünlü", "sentence_en": "This is famous.", "sentence_tr": "Bu ünlü."},
    {"word": "fast", "type": "adjective", "meaning": "hızlı", "sentence_en": "This is fast.", "sentence_tr": "Bu hızlı."},
    {"word": "fat", "type": "adjective", "meaning": "şişman", "sentence_en": "This is fat.", "sentence_tr": "Bu şişman."},
    {"word": "final", "type": "adjective", "meaning": "son", "sentence_en": "This is final.", "sentence_tr": "Bu son."},
    {"word": "fine", "type": "adjective", "meaning": "iyi", "sentence_en": "This is fine.", "sentence_tr": "Bu iyi."},
    {"word": "flat", "type": "adjective", "meaning": "düz", "sentence_en": "This is flat.", "sentence_tr": "Bu düz."},
    {"word": "foreign", "type": "adjective", "meaning": "yabancı", "sentence_en": "This is foreign.", "sentence_tr": "Bu yabancı."},
    {"word": "free", "type": "adjective", "meaning": "ücretsiz", "sentence_en": "This is free.", "sentence_tr": "Bu ücretsiz."},
    {"word": "fresh", "type": "adjective", "meaning": "taze", "sentence_en": "This is fresh.", "sentence_tr": "Bu taze."},
    {"word": "full", "type": "adjective", "meaning": "dolu", "sentence_en": "This is full.", "sentence_tr": "Bu dolu."},
    {"word": "funny", "type": "adjective", "meaning": "komik", "sentence_en": "This is funny.", "sentence_tr": "Bu komik."},
    {"word": "future", "type": "adjective", "meaning": "gelecek", "sentence_en": "This is future.", "sentence_tr": "Bu gelecek."},
    {"word": "general", "type": "adjective", "meaning": "genel", "sentence_en": "This is general.", "sentence_tr": "Bu genel."},
    {"word": "good", "type": "adjective", "meaning": "iyi", "sentence_en": "This is good.", "sentence_tr": "Bu iyi."},
    {"word": "great", "type": "adjective", "meaning": "harika", "sentence_en": "This is great.", "sentence_tr": "Bu harika."},
    {"word": "green", "type": "adjective", "meaning": "yeşil", "sentence_en": "This is green.", "sentence_tr": "Bu yeşil."},
    {"word": "happy", "type": "adjective", "meaning": "mutlu", "sentence_en": "This is happy.", "sentence_tr": "Bu mutlu."},
    {"word": "hard", "type": "adjective", "meaning": "sert", "sentence_en": "This is hard.", "sentence_tr": "Bu sert."},
    {"word": "heavy", "type": "adjective", "meaning": "ağır", "sentence_en": "This is heavy.", "sentence_tr": "Bu ağır."},
    {"word": "high", "type": "adjective", "meaning": "yüksek", "sentence_en": "This is high.", "sentence_tr": "Bu yüksek."},
    {"word": "hot", "type": "adjective", "meaning": "sıcak", "sentence_en": "This is hot.", "sentence_tr": "Bu sıcak."},
    {"word": "huge", "type": "adjective", "meaning": "dev", "sentence_en": "This is huge.", "sentence_tr": "Bu dev."},
    {"word": "human", "type": "adjective", "meaning": "insan", "sentence_en": "This is human.", "sentence_tr": "Bu insan."},
    {"word": "immediate", "type": "adjective", "meaning": "acil", "sentence_en": "This is immediate.", "sentence_tr": "Bu acil."},
    {"word": "important", "type": "adjective", "meaning": "önemli", "sentence_en": "This is important.", "sentence_tr": "Bu önemli."},
    {"word": "impossible", "type": "adjective", "meaning": "imkansız", "sentence_en": "This is impossible.", "sentence_tr": "Bu imkansız."},
    {"word": "independent", "type": "adjective", "meaning": "bağımsız", "sentence_en": "This is independent.", "sentence_tr": "Bu bağımsız."},
    {"word": "individual", "type": "adjective", "meaning": "bireysel", "sentence_en": "This is individual.", "sentence_tr": "Bu bireysel."},
    {"word": "industrial", "type": "adjective", "meaning": "endüstriyel", "sentence_en": "This is industrial.", "sentence_tr": "Bu endüstriyel."},
    {"word": "inexpensive", "type": "adjective", "meaning": "ucuz", "sentence_en": "This is inexpensive.", "sentence_tr": "Bu ucuz."},
    {"word": "international", "type": "adjective", "meaning": "uluslararası", "sentence_en": "This is international.", "sentence_tr": "Bu uluslararası."},
    {"word": "large", "type": "adjective", "meaning": "büyük", "sentence_en": "This is large.", "sentence_tr": "Bu büyük."},
    {"word": "late", "type": "adjective", "meaning": "geç", "sentence_en": "This is late.", "sentence_tr": "Bu geç."},
    {"word": "legal", "type": "adjective", "meaning": "yasal", "sentence_en": "This is legal.", "sentence_tr": "Bu yasal."},
    {"word": "light", "type": "adjective", "meaning": "hafif", "sentence_en": "This is light.", "sentence_tr": "Bu hafif."},
    {"word": "local", "type": "adjective", "meaning": "yerel", "sentence_en": "This is local.", "sentence_tr": "Bu yerel."},
    {"word": "long", "type": "adjective", "meaning": "uzun", "sentence_en": "This is long.", "sentence_tr": "Bu uzun."},
    {"word": "low", "type": "adjective", "meaning": "düşük", "sentence_en": "This is low.", "sentence_tr": "Bu düşük."},
    {"word": "main", "type": "adjective", "meaning": "ana", "sentence_en": "This is main.", "sentence_tr": "Bu ana."},
    {"word": "major", "type": "adjective", "meaning": "büyük", "sentence_en": "This is major.", "sentence_tr": "Bu büyük."},
    {"word": "medical", "type": "adjective", "meaning": "tıbbi", "sentence_en": "This is medical.", "sentence_tr": "Bu tıbbi."},
    {"word": "mental", "type": "adjective", "meaning": "zihinsel", "sentence_en": "This is mental.", "sentence_tr": "Bu zihinsel."},
    {"word": "minor", "type": "adjective", "meaning": "küçük", "sentence_en": "This is minor.", "sentence_tr": "Bu küçük."},
    {"word": "modern", "type": "adjective", "meaning": "modern", "sentence_en": "This is modern.", "sentence_tr": "Bu modern."},
    {"word": "natural", "type": "adjective", "meaning": "doğal", "sentence_en": "This is natural.", "sentence_tr": "Bu doğal."},
    {"word": "necessary", "type": "adjective", "meaning": "gerekli", "sentence_en": "This is necessary.", "sentence_tr": "Bu gerekli."},
    {"word": "new", "type": "adjective", "meaning": "yeni", "sentence_en": "This is new.", "sentence_tr": "Bu yeni."},
    {"word": "normal", "type": "adjective", "meaning": "normal", "sentence_en": "This is normal.", "sentence_tr": "Bu normal."},
    {"word": "official", "type": "adjective", "meaning": "resmi", "sentence_en": "This is official.", "sentence_tr": "Bu resmi."},
    {"word": "old", "type": "adjective", "meaning": "eski", "sentence_en": "This is old.", "sentence_tr": "Bu eski."},
    {"word": "open", "type": "adjective", "meaning": "açık", "sentence_en": "This is open.", "sentence_tr": "Bu açık."},
    {"word": "original", "type": "adjective", "meaning": "orijinal", "sentence_en": "This is original.", "sentence_tr": "Bu orijinal."},
    {"word": "personal", "type": "adjective", "meaning": "kişisel", "sentence_en": "This is personal.", "sentence_tr": "Bu kişisel."},
    {"word": "physical", "type": "adjective", "meaning": "fiziksel", "sentence_en": "This is physical.", "sentence_tr": "Bu fiziksel."},
    {"word": "political", "type": "adjective", "meaning": "siyasi", "sentence_en": "This is political.", "sentence_tr": "Bu siyasi."},
    {"word": "poor", "type": "adjective", "meaning": "fakir", "sentence_en": "This is poor.", "sentence_tr": "Bu fakir."},
    {"word": "popular", "type": "adjective", "meaning": "popüler", "sentence_en": "This is popular.", "sentence_tr": "Bu popüler."},
    {"word": "positive", "type": "adjective", "meaning": "pozitif", "sentence_en": "This is positive.", "sentence_tr": "Bu pozitif."},
    {"word": "possible", "type": "adjective", "meaning": "mümkün", "sentence_en": "This is possible.", "sentence_tr": "Bu mümkün."},
    {"word": "powerful", "type": "adjective", "meaning": "güçlü", "sentence_en": "This is powerful.", "sentence_tr": "Bu güçlü."},
    {"word": "practical", "type": "adjective", "meaning": "pratik", "sentence_en": "This is practical.", "sentence_tr": "Bu pratik."},
    {"word": "private", "type": "adjective", "meaning": "özel", "sentence_en": "This is private.", "sentence_tr": "Bu özel."},
    {"word": "professional", "type": "adjective", "meaning": "profesyonel", "sentence_en": "This is professional.", "sentence_tr": "Bu profesyonel."},
    {"word": "public", "type": "adjective", "meaning": "halka açık", "sentence_en": "This is public.", "sentence_tr": "Bu halka açık."},
    {"word": "quick", "type": "adjective", "meaning": "hızlı", "sentence_en": "This is quick.", "sentence_tr": "Bu hızlı."},
    {"word": "quiet", "type": "adjective", "meaning": "sessiz", "sentence_en": "This is quiet.", "sentence_tr": "Bu sessiz."},
    {"word": "ready", "type": "adjective", "meaning": "hazır", "sentence_en": "This is ready.", "sentence_tr": "Bu hazır."},
    {"word": "real", "type": "adjective", "meaning": "gerçek", "sentence_en": "This is real.", "sentence_tr": "Bu gerçek."},
    {"word": "recent", "type": "adjective", "meaning": "son", "sentence_en": "This is recent.", "sentence_tr": "Bu son."},
    {"word": "red", "type": "adjective", "meaning": "kırmızı", "sentence_en": "This is red.", "sentence_tr": "Bu kırmızı."},
    {"word": "regular", "type": "adjective", "meaning": "düzenli", "sentence_en": "This is regular.", "sentence_tr": "Bu düzenli."},
    {"word": "rich", "type": "adjective", "meaning": "zengin", "sentence_en": "This is rich.", "sentence_tr": "Bu zengin."},
    {"word": "right", "type": "adjective", "meaning": "doğru", "sentence_en": "This is right.", "sentence_tr": "Bu doğru."},
    {"word": "round", "type": "adjective", "meaning": "yuvarlak", "sentence_en": "This is round.", "sentence_tr": "Bu yuvarlak."},
    {"word": "safe", "type": "adjective", "meaning": "güvenli", "sentence_en": "This is safe.", "sentence_tr": "Bu güvenli."},
    {"word": "same", "type": "adjective", "meaning": "aynı", "sentence_en": "This is same.", "sentence_tr": "Bu aynı."},
    {"word": "serious", "type": "adjective", "meaning": "ciddi", "sentence_en": "This is serious.", "sentence_tr": "Bu ciddi."},
    {"word": "short", "type": "adjective", "meaning": "kısa", "sentence_en": "This is short.", "sentence_tr": "Bu kısa."},
    {"word": "simple", "type": "adjective", "meaning": "basit", "sentence_en": "This is simple.", "sentence_tr": "Bu basit."},
    {"word": "small", "type": "adjective", "meaning": "küçük", "sentence_en": "This is small.", "sentence_tr": "Bu küçük."},
    {"word": "soft", "type": "adjective", "meaning": "yumuşak", "sentence_en": "This is soft.", "sentence_tr": "Bu yumuşak."},
    {"word": "special", "type": "adjective", "meaning": "özel", "sentence_en": "This is special.", "sentence_tr": "Bu özel."},
    {"word": "strong", "type": "adjective", "meaning": "güçlü", "sentence_en": "This is strong.", "sentence_tr": "Bu güçlü."},
    {"word": "sure", "type": "adjective", "meaning": "emin", "sentence_en": "This is sure.", "sentence_tr": "Bu emin."},
    {"word": "sweet", "type": "adjective", "meaning": "tatlı", "sentence_en": "This is sweet.", "sentence_tr": "Bu tatlı."},
    {"word": "tall", "type": "adjective", "meaning": "uzun", "sentence_en": "This is tall.", "sentence_tr": "Bu uzun."},
    {"word": "thick", "type": "adjective", "meaning": "kalın", "sentence_en": "This is thick.", "sentence_tr": "Bu kalın."},
    {"word": "thin", "type": "adjective", "meaning": "ince", "sentence_en": "This is thin.", "sentence_tr": "Bu ince."},
    {"word": "tired", "type": "adjective", "meaning": "yorgun", "sentence_en": "This is tired.", "sentence_tr": "Bu yorgun."},
    {"word": "true", "type": "adjective", "meaning": "doğru", "sentence_en": "This is true.", "sentence_tr": "Bu doğru."},
    {"word": "useful", "type": "adjective", "meaning": "faydalı", "sentence_en": "This is useful.", "sentence_tr": "Bu faydalı."},
    {"word": "warm", "type": "adjective", "meaning": "ılık", "sentence_en": "This is warm.", "sentence_tr": "Bu ılık."},
    {"word": "weak", "type": "adjective", "meaning": "zayıf", "sentence_en": "This is weak.", "sentence_tr": "Bu zayıf."},
    {"word": "white", "type": "adjective", "meaning": "beyaz", "sentence_en": "This is white.", "sentence_tr": "Bu beyaz."},
    {"word": "wide", "type": "adjective", "meaning": "geniş", "sentence_en": "This is wide.", "sentence_tr": "Bu geniş."},
    {"word": "wild", "type": "adjective", "meaning": "vahşi", "sentence_en": "This is wild.", "sentence_tr": "Bu vahşi."},
    {"word": "wrong", "type": "adjective", "meaning": "yanlış", "sentence_en": "This is wrong.", "sentence_tr": "Bu yanlış."},
    {"word": "yellow", "type": "adjective", "meaning": "sarı", "sentence_en": "This is yellow.", "sentence_tr": "Bu sarı."},
    {"word": "young", "type": "adjective", "meaning": "genç", "sentence_en": "This is young.", "sentence_tr": "Bu genç."}
]

# Tüm kelimeleri birleştir
all_words = existing_words + additional_words

# Dosyaya yaz
with open('public/words.json', 'w', encoding='utf-8') as f:
    json.dump(all_words, f, ensure_ascii=False, indent=2)

print(f"Toplam {len(all_words)} kelime oluşturuldu!")
print("Dosya: public/words.json") 