import json
import random

# Mevcut kelimeleri oku
with open('public/words.json', 'r', encoding='utf-8') as f:
    existing_words = json.load(f)

print(f"Mevcut kelime sayısı: {len(existing_words)}")

# Daha fazla kelime ekleyelim (3000'e yakın olacak şekilde)
additional_words = [
    # Daha fazla Verbs
    {"word": "accept", "type": "verb", "meaning": "kabul etmek", "sentence_en": "I accept your offer.", "sentence_tr": "Teklifini kabul ediyorum."},
    {"word": "add", "type": "verb", "meaning": "eklemek", "sentence_en": "Please add some salt.", "sentence_tr": "Lütfen biraz tuz ekle."},
    {"word": "admit", "type": "verb", "meaning": "kabul etmek", "sentence_en": "I admit my mistake.", "sentence_tr": "Hatamı kabul ediyorum."},
    {"word": "agree", "type": "verb", "meaning": "katılmak", "sentence_en": "I agree with you.", "sentence_tr": "Sana katılıyorum."},
    {"word": "allow", "type": "verb", "meaning": "izin vermek", "sentence_en": "Please allow me to help.", "sentence_tr": "Lütfen yardım etmeme izin ver."},
    {"word": "answer", "type": "verb", "meaning": "cevaplamak", "sentence_en": "Please answer the question.", "sentence_tr": "Lütfen soruyu cevapla."},
    {"word": "appear", "type": "verb", "meaning": "görünmek", "sentence_en": "He appeared suddenly.", "sentence_tr": "Aniden göründü."},
    {"word": "apply", "type": "verb", "meaning": "başvurmak", "sentence_en": "I will apply for the job.", "sentence_tr": "İşe başvuracağım."},
    {"word": "argue", "type": "verb", "meaning": "tartışmak", "sentence_en": "They argued about politics.", "sentence_tr": "Siyaset hakkında tartıştılar."},
    {"word": "arrive", "type": "verb", "meaning": "varmak", "sentence_en": "When will you arrive?", "sentence_tr": "Ne zaman varacaksın?"},
    {"word": "ask", "type": "verb", "meaning": "sormak", "sentence_en": "Can I ask you a question?", "sentence_tr": "Sana bir soru sorabilir miyim?"},
    {"word": "avoid", "type": "verb", "meaning": "kaçınmak", "sentence_en": "Try to avoid trouble.", "sentence_tr": "Beladan kaçınmaya çalış."},
    {"word": "begin", "type": "verb", "meaning": "başlamak", "sentence_en": "Let's begin the meeting.", "sentence_tr": "Toplantıya başlayalım."},
    {"word": "belong", "type": "verb", "meaning": "ait olmak", "sentence_en": "This book belongs to me.", "sentence_tr": "Bu kitap bana ait."},
    {"word": "break", "type": "verb", "meaning": "kırmak", "sentence_en": "Don't break the glass.", "sentence_tr": "Bardağı kırma."},
    {"word": "bring", "type": "verb", "meaning": "getirmek", "sentence_en": "Please bring your book.", "sentence_tr": "Lütfen kitabını getir."},
    {"word": "build", "type": "verb", "meaning": "inşa etmek", "sentence_en": "They will build a house.", "sentence_tr": "Bir ev inşa edecekler."},
    {"word": "buy", "type": "verb", "meaning": "satın almak", "sentence_en": "I want to buy a car.", "sentence_tr": "Bir araba satın almak istiyorum."},
    {"word": "call", "type": "verb", "meaning": "aramak", "sentence_en": "Please call me later.", "sentence_tr": "Lütfen beni sonra ara."},
    {"word": "carry", "type": "verb", "meaning": "taşımak", "sentence_en": "Can you carry this bag?", "sentence_tr": "Bu çantayı taşıyabilir misin?"},
    {"word": "catch", "type": "verb", "meaning": "yakalamak", "sentence_en": "Try to catch the ball.", "sentence_tr": "Topu yakalamaya çalış."},
    {"word": "change", "type": "verb", "meaning": "değiştirmek", "sentence_en": "I need to change my clothes.", "sentence_tr": "Kıyafetlerimi değiştirmem gerekiyor."},
    {"word": "check", "type": "verb", "meaning": "kontrol etmek", "sentence_en": "Please check the time.", "sentence_tr": "Lütfen saati kontrol et."},
    {"word": "close", "type": "verb", "meaning": "kapatmak", "sentence_en": "Please close the door.", "sentence_tr": "Lütfen kapıyı kapat."},
    {"word": "come", "type": "verb", "meaning": "gelmek", "sentence_en": "Please come here.", "sentence_tr": "Lütfen buraya gel."},
    {"word": "consider", "type": "verb", "meaning": "düşünmek", "sentence_en": "Please consider my offer.", "sentence_tr": "Lütfen teklifimi düşün."},
    {"word": "continue", "type": "verb", "meaning": "devam etmek", "sentence_en": "Please continue reading.", "sentence_tr": "Lütfen okumaya devam et."},
    {"word": "create", "type": "verb", "meaning": "yaratmak", "sentence_en": "She will create a masterpiece.", "sentence_tr": "Bir başyapıt yaratacak."},
    {"word": "cut", "type": "verb", "meaning": "kesmek", "sentence_en": "Please cut the paper.", "sentence_tr": "Lütfen kağıdı kes."},
    {"word": "decide", "type": "verb", "meaning": "karar vermek", "sentence_en": "You must decide now.", "sentence_tr": "Şimdi karar vermelisin."},
    {"word": "develop", "type": "verb", "meaning": "geliştirmek", "sentence_en": "We need to develop this idea.", "sentence_tr": "Bu fikri geliştirmemiz gerekiyor."},
    {"word": "die", "type": "verb", "meaning": "ölmek", "sentence_en": "The plant will die without water.", "sentence_tr": "Bitki su olmadan ölecek."},
    {"word": "draw", "type": "verb", "meaning": "çizmek", "sentence_en": "Can you draw a picture?", "sentence_tr": "Bir resim çizebilir misin?"},
    {"word": "drink", "type": "verb", "meaning": "içmek", "sentence_en": "Please drink some water.", "sentence_tr": "Lütfen biraz su iç."},
    {"word": "drive", "type": "verb", "meaning": "sürmek", "sentence_en": "I can drive a car.", "sentence_tr": "Araba sürebilirim."},
    {"word": "eat", "type": "verb", "meaning": "yemek", "sentence_en": "Let's eat dinner.", "sentence_tr": "Akşam yemeği yiyelim."},
    {"word": "end", "type": "verb", "meaning": "bitirmek", "sentence_en": "The movie will end soon.", "sentence_tr": "Film yakında bitecek."},
    {"word": "expect", "type": "verb", "meaning": "beklemek", "sentence_en": "I expect you to come.", "sentence_tr": "Gelmeni bekliyorum."},
    {"word": "fall", "type": "verb", "meaning": "düşmek", "sentence_en": "Be careful not to fall.", "sentence_tr": "Düşmemeye dikkat et."},
    {"word": "feel", "type": "verb", "meaning": "hissetmek", "sentence_en": "How do you feel?", "sentence_tr": "Nasıl hissediyorsun?"},
    {"word": "find", "type": "verb", "meaning": "bulmak", "sentence_en": "Can you find my keys?", "sentence_tr": "Anahtarlarımı bulabilir misin?"},
    {"word": "finish", "type": "verb", "meaning": "bitirmek", "sentence_en": "Please finish your homework.", "sentence_tr": "Lütfen ödevini bitir."},
    {"word": "forget", "type": "verb", "meaning": "unutmak", "sentence_en": "Don't forget to call.", "sentence_tr": "Aramayı unutma."},
    {"word": "get", "type": "verb", "meaning": "almak", "sentence_en": "I need to get some milk.", "sentence_tr": "Biraz süt almam gerekiyor."},
    {"word": "go", "type": "verb", "meaning": "gitmek", "sentence_en": "Let's go home.", "sentence_tr": "Eve gidelim."},
    {"word": "grow", "type": "verb", "meaning": "büyümek", "sentence_en": "Plants grow in sunlight.", "sentence_tr": "Bitkiler güneş ışığında büyür."},
    {"word": "happen", "type": "verb", "meaning": "olmak", "sentence_en": "What will happen next?", "sentence_tr": "Sırada ne olacak?"},
    {"word": "have", "type": "verb", "meaning": "sahip olmak", "sentence_en": "I have a car.", "sentence_tr": "Bir arabam var."},
    {"word": "hear", "type": "verb", "meaning": "duymak", "sentence_en": "Can you hear me?", "sentence_tr": "Beni duyabiliyor musun?"},
    {"word": "hold", "type": "verb", "meaning": "tutmak", "sentence_en": "Please hold my hand.", "sentence_tr": "Lütfen elimi tut."},
    {"word": "include", "type": "verb", "meaning": "dahil etmek", "sentence_en": "Please include everyone.", "sentence_tr": "Lütfen herkesi dahil et."},
    {"word": "increase", "type": "verb", "meaning": "artırmak", "sentence_en": "We need to increase sales.", "sentence_tr": "Satışları artırmamız gerekiyor."},
    {"word": "indicate", "type": "verb", "meaning": "göstermek", "sentence_en": "The sign indicates the way.", "sentence_tr": "İşaret yolu gösteriyor."},
    {"word": "introduce", "type": "verb", "meaning": "tanıtmak", "sentence_en": "Let me introduce myself.", "sentence_tr": "Kendimi tanıtayım."},
    {"word": "involve", "type": "verb", "meaning": "dahil etmek", "sentence_en": "This will involve everyone.", "sentence_tr": "Bu herkesi dahil edecek."},
    {"word": "keep", "type": "verb", "meaning": "saklamak", "sentence_en": "Please keep this secret.", "sentence_tr": "Lütfen bu sırrı sakla."},
    {"word": "know", "type": "verb", "meaning": "bilmek", "sentence_en": "I know the answer.", "sentence_tr": "Cevabı biliyorum."},
    {"word": "leave", "type": "verb", "meaning": "ayrılmak", "sentence_en": "I must leave now.", "sentence_tr": "Şimdi ayrılmam gerekiyor."},
    {"word": "let", "type": "verb", "meaning": "izin vermek", "sentence_en": "Let me help you.", "sentence_tr": "Sana yardım etmeme izin ver."},
    {"word": "like", "type": "verb", "meaning": "beğenmek", "sentence_en": "I like this movie.", "sentence_tr": "Bu filmi beğeniyorum."},
    {"word": "live", "type": "verb", "meaning": "yaşamak", "sentence_en": "I live in Istanbul.", "sentence_tr": "İstanbul'da yaşıyorum."},
    {"word": "look", "type": "verb", "meaning": "bakmak", "sentence_en": "Look at this picture.", "sentence_tr": "Bu resme bak."},
    {"word": "lose", "type": "verb", "meaning": "kaybetmek", "sentence_en": "Don't lose your keys.", "sentence_tr": "Anahtarlarını kaybetme."},
    {"word": "love", "type": "verb", "meaning": "sevmek", "sentence_en": "I love you.", "sentence_tr": "Seni seviyorum."},
    {"word": "make", "type": "verb", "meaning": "yapmak", "sentence_en": "I will make dinner.", "sentence_tr": "Akşam yemeği yapacağım."},
    {"word": "mean", "type": "verb", "meaning": "anlamına gelmek", "sentence_en": "What does this word mean?", "sentence_tr": "Bu kelime ne anlama geliyor?"},
    {"word": "meet", "type": "verb", "meaning": "buluşmak", "sentence_en": "Let's meet tomorrow.", "sentence_tr": "Yarın buluşalım."},
    {"word": "move", "type": "verb", "meaning": "hareket etmek", "sentence_en": "Please move your car.", "sentence_tr": "Lütfen arabanı hareket ettir."},
    {"word": "need", "type": "verb", "meaning": "ihtiyaç duymak", "sentence_en": "I need some help.", "sentence_tr": "Biraz yardıma ihtiyacım var."},
    {"word": "open", "type": "verb", "meaning": "açmak", "sentence_en": "Please open the door.", "sentence_tr": "Lütfen kapıyı aç."},
    {"word": "pass", "type": "verb", "meaning": "geçmek", "sentence_en": "Please pass the salt.", "sentence_tr": "Lütfen tuzu geç."},
    {"word": "pay", "type": "verb", "meaning": "ödemek", "sentence_en": "I will pay for dinner.", "sentence_tr": "Akşam yemeğini ödeyeceğim."},
    {"word": "play", "type": "verb", "meaning": "oynamak", "sentence_en": "Let's play a game.", "sentence_tr": "Bir oyun oynayalım."},
    {"word": "point", "type": "verb", "meaning": "işaret etmek", "sentence_en": "Please point to the exit.", "sentence_tr": "Lütfen çıkışı işaret et."},
    {"word": "provide", "type": "verb", "meaning": "sağlamak", "sentence_en": "We will provide food.", "sentence_tr": "Yemek sağlayacağız."},
    {"word": "put", "type": "verb", "meaning": "koymak", "sentence_en": "Please put the book on the table.", "sentence_tr": "Lütfen kitabı masaya koy."},
    {"word": "read", "type": "verb", "meaning": "okumak", "sentence_en": "I like to read books.", "sentence_tr": "Kitap okumayı seviyorum."},
    {"word": "reach", "type": "verb", "meaning": "ulaşmak", "sentence_en": "Can you reach the top?", "sentence_tr": "Tepeye ulaşabilir misin?"},
    {"word": "realize", "type": "verb", "meaning": "fark etmek", "sentence_en": "I realize my mistake.", "sentence_tr": "Hatamı fark ettim."},
    {"word": "receive", "type": "verb", "meaning": "almak", "sentence_en": "I received your letter.", "sentence_tr": "Mektubunu aldım."},
    {"word": "recognize", "type": "verb", "meaning": "tanımak", "sentence_en": "I recognize you.", "sentence_tr": "Seni tanıyorum."},
    {"word": "reduce", "type": "verb", "meaning": "azaltmak", "sentence_en": "We need to reduce costs.", "sentence_tr": "Maliyetleri azaltmamız gerekiyor."},
    {"word": "remain", "type": "verb", "meaning": "kalmak", "sentence_en": "Please remain seated.", "sentence_tr": "Lütfen oturun."},
    {"word": "remember", "type": "verb", "meaning": "hatırlamak", "sentence_en": "Do you remember me?", "sentence_tr": "Beni hatırlıyor musun?"},
    {"word": "remove", "type": "verb", "meaning": "kaldırmak", "sentence_en": "Please remove your shoes.", "sentence_tr": "Lütfen ayakkabılarını çıkar."},
    {"word": "replace", "type": "verb", "meaning": "değiştirmek", "sentence_en": "We need to replace the battery.", "sentence_tr": "Pili değiştirmemiz gerekiyor."},
    {"word": "represent", "type": "verb", "meaning": "temsil etmek", "sentence_en": "He represents the company.", "sentence_tr": "Şirketi temsil ediyor."},
    {"word": "require", "type": "verb", "meaning": "gerektirmek", "sentence_en": "This job requires experience.", "sentence_tr": "Bu iş deneyim gerektiriyor."},
    {"word": "return", "type": "verb", "meaning": "dönmek", "sentence_en": "I will return soon.", "sentence_tr": "Yakında döneceğim."},
    {"word": "run", "type": "verb", "meaning": "koşmak", "sentence_en": "I like to run in the morning.", "sentence_tr": "Sabahları koşmayı seviyorum."},
    {"word": "say", "type": "verb", "meaning": "söylemek", "sentence_en": "What did you say?", "sentence_tr": "Ne söyledin?"},
    {"word": "see", "type": "verb", "meaning": "görmek", "sentence_en": "Can you see the bird?", "sentence_tr": "Kuşu görebiliyor musun?"},
    {"word": "seem", "type": "verb", "meaning": "görünmek", "sentence_en": "You seem tired.", "sentence_tr": "Yorgun görünüyorsun."},
    {"word": "send", "type": "verb", "meaning": "göndermek", "sentence_en": "I will send you an email.", "sentence_tr": "Sana bir email göndereceğim."},
    {"word": "serve", "type": "verb", "meaning": "hizmet vermek", "sentence_en": "We serve breakfast.", "sentence_tr": "Kahvaltı servisi veriyoruz."},
    {"word": "set", "type": "verb", "meaning": "koymak", "sentence_en": "Please set the table.", "sentence_tr": "Lütfen masayı kur."},
    {"word": "show", "type": "verb", "meaning": "göstermek", "sentence_en": "Can you show me the way?", "sentence_tr": "Bana yolu gösterebilir misin?"},
    {"word": "sit", "type": "verb", "meaning": "oturmak", "sentence_en": "Please sit down.", "sentence_tr": "Lütfen oturun."},
    {"word": "sleep", "type": "verb", "meaning": "uyumak", "sentence_en": "I need to sleep.", "sentence_tr": "Uyumam gerekiyor."},
    {"word": "speak", "type": "verb", "meaning": "konuşmak", "sentence_en": "I can speak English.", "sentence_tr": "İngilizce konuşabilirim."},
    {"word": "spend", "type": "verb", "meaning": "harcamak", "sentence_en": "I spend money on books.", "sentence_tr": "Kitap için para harcıyorum."},
    {"word": "stand", "type": "verb", "meaning": "ayakta durmak", "sentence_en": "Please stand up.", "sentence_tr": "Lütfen ayağa kalk."},
    {"word": "start", "type": "verb", "meaning": "başlamak", "sentence_en": "Let's start the game.", "sentence_tr": "Oyunu başlatalım."},
    {"word": "stop", "type": "verb", "meaning": "durdurmak", "sentence_en": "Please stop talking.", "sentence_tr": "Lütfen konuşmayı durdur."},
    {"word": "suggest", "type": "verb", "meaning": "öneri vermek", "sentence_en": "I suggest we go home.", "sentence_tr": "Eve gitmeyi öneriyorum."},
    {"word": "support", "type": "verb", "meaning": "desteklemek", "sentence_en": "I support your idea.", "sentence_tr": "Fikrini destekliyorum."},
    {"word": "take", "type": "verb", "meaning": "almak", "sentence_en": "Please take a seat.", "sentence_tr": "Lütfen oturun."},
    {"word": "talk", "type": "verb", "meaning": "konuşmak", "sentence_en": "Let's talk about it.", "sentence_tr": "Bunun hakkında konuşalım."},
    {"word": "tell", "type": "verb", "meaning": "söylemek", "sentence_en": "Tell me the truth.", "sentence_tr": "Bana gerçeği söyle."},
    {"word": "think", "type": "verb", "meaning": "düşünmek", "sentence_en": "I think about you.", "sentence_tr": "Seni düşünüyorum."},
    {"word": "try", "type": "verb", "meaning": "denemek", "sentence_en": "Try this food.", "sentence_tr": "Bu yemeği dene."},
    {"word": "turn", "type": "verb", "meaning": "dönmek", "sentence_en": "Please turn left.", "sentence_tr": "Lütfen sola dön."},
    {"word": "understand", "type": "verb", "meaning": "anlamak", "sentence_en": "I don't understand.", "sentence_tr": "Anlamıyorum."},
    {"word": "use", "type": "verb", "meaning": "kullanmak", "sentence_en": "I use my phone.", "sentence_tr": "Telefonumu kullanıyorum."},
    {"word": "wait", "type": "verb", "meaning": "beklemek", "sentence_en": "Please wait here.", "sentence_tr": "Lütfen burada bekle."},
    {"word": "walk", "type": "verb", "meaning": "yürümek", "sentence_en": "I walk to work.", "sentence_tr": "İşe yürüyerek gidiyorum."},
    {"word": "watch", "type": "verb", "meaning": "izlemek", "sentence_en": "I watch TV.", "sentence_tr": "TV izliyorum."},
    {"word": "wear", "type": "verb", "meaning": "giymek", "sentence_en": "I wear a coat.", "sentence_tr": "Bir palto giyiyorum."},
    {"word": "win", "type": "verb", "meaning": "kazanmak", "sentence_en": "I want to win.", "sentence_tr": "Kazanmak istiyorum."},
    {"word": "write", "type": "verb", "meaning": "yazmak", "sentence_en": "I write letters.", "sentence_tr": "Mektup yazıyorum."}
]

# Tüm kelimeleri birleştir
all_words = existing_words + additional_words

# Dosyaya yaz
with open('public/words.json', 'w', encoding='utf-8') as f:
    json.dump(all_words, f, ensure_ascii=False, indent=2)

print(f"Toplam {len(all_words)} kelime oluşturuldu!")
print("Dosya: public/words.json") 