import json
import random

# Mevcut kelimeleri oku
with open('public/words.json', 'r', encoding='utf-8') as f:
    existing_words = json.load(f)

print(f"Mevcut kelime sayısı: {len(existing_words)}")

# Daha fazla kelime ekleyelim (3000'e yakın olacak şekilde)
additional_words = [
    # Daha fazla Nouns
    {"word": "ability", "type": "noun", "meaning": "yetenek", "sentence_en": "She has the ability to learn quickly.", "sentence_tr": "Hızlı öğrenme yeteneği var."},
    {"word": "account", "type": "noun", "meaning": "hesap", "sentence_en": "I have a bank account.", "sentence_tr": "Bir banka hesabım var."},
    {"word": "action", "type": "noun", "meaning": "eylem", "sentence_en": "We need to take action.", "sentence_tr": "Eylem almamız gerekiyor."},
    {"word": "activity", "type": "noun", "meaning": "aktivite", "sentence_en": "This is a fun activity.", "sentence_tr": "Bu eğlenceli bir aktivite."},
    {"word": "address", "type": "noun", "meaning": "adres", "sentence_en": "What is your address?", "sentence_tr": "Adresin nedir?"},
    {"word": "advantage", "type": "noun", "meaning": "avantaj", "sentence_en": "This gives us an advantage.", "sentence_tr": "Bu bize bir avantaj sağlıyor."},
    {"word": "advertisement", "type": "noun", "meaning": "reklam", "sentence_en": "I saw an advertisement on TV.", "sentence_tr": "TV'de bir reklam gördüm."},
    {"word": "advice", "type": "noun", "meaning": "tavsiye", "sentence_en": "Can you give me some advice?", "sentence_tr": "Bana biraz tavsiye verebilir misin?"},
    {"word": "age", "type": "noun", "meaning": "yaş", "sentence_en": "What is your age?", "sentence_tr": "Yaşın kaç?"},
    {"word": "agreement", "type": "noun", "meaning": "anlaşma", "sentence_en": "We reached an agreement.", "sentence_tr": "Bir anlaşmaya vardık."},
    {"word": "air", "type": "noun", "meaning": "hava", "sentence_en": "The air is fresh.", "sentence_tr": "Hava taze."},
    {"word": "amount", "type": "noun", "meaning": "miktar", "sentence_en": "What is the total amount?", "sentence_tr": "Toplam miktar nedir?"},
    {"word": "animal", "type": "noun", "meaning": "hayvan", "sentence_en": "I love animals.", "sentence_tr": "Hayvanları seviyorum."},
    {"word": "answer", "type": "noun", "meaning": "cevap", "sentence_en": "What is the answer?", "sentence_tr": "Cevap nedir?"},
    {"word": "area", "type": "noun", "meaning": "alan", "sentence_en": "This is a large area.", "sentence_tr": "Bu büyük bir alan."},
    {"word": "arm", "type": "noun", "meaning": "kol", "sentence_en": "My arm hurts.", "sentence_tr": "Kolum ağrıyor."},
    {"word": "art", "type": "noun", "meaning": "sanat", "sentence_en": "I love art.", "sentence_tr": "Sanatı seviyorum."},
    {"word": "article", "type": "noun", "meaning": "makale", "sentence_en": "I read an interesting article.", "sentence_tr": "İlginç bir makale okudum."},
    {"word": "attention", "type": "noun", "meaning": "dikkat", "sentence_en": "Pay attention to the teacher.", "sentence_tr": "Öğretmene dikkat et."},
    {"word": "author", "type": "noun", "meaning": "yazar", "sentence_en": "Who is the author of this book?", "sentence_tr": "Bu kitabın yazarı kim?"},
    {"word": "baby", "type": "noun", "meaning": "bebek", "sentence_en": "The baby is sleeping.", "sentence_tr": "Bebek uyuyor."},
    {"word": "back", "type": "noun", "meaning": "sırt", "sentence_en": "My back hurts.", "sentence_tr": "Sırtım ağrıyor."},
    {"word": "bag", "type": "noun", "meaning": "çanta", "sentence_en": "I carry a bag.", "sentence_tr": "Bir çanta taşıyorum."},
    {"word": "ball", "type": "noun", "meaning": "top", "sentence_en": "Let's play ball.", "sentence_tr": "Top oynayalım."},
    {"word": "bank", "type": "noun", "meaning": "banka", "sentence_en": "I go to the bank.", "sentence_tr": "Bankaya gidiyorum."},
    {"word": "base", "type": "noun", "meaning": "temel", "sentence_en": "This is the base of the building.", "sentence_tr": "Bu binanın temeli."},
    {"word": "battle", "type": "noun", "meaning": "savaş", "sentence_en": "This was a difficult battle.", "sentence_tr": "Bu zor bir savaştı."},
    {"word": "beach", "type": "noun", "meaning": "sahil", "sentence_en": "I love the beach.", "sentence_tr": "Sahili seviyorum."},
    {"word": "bed", "type": "noun", "meaning": "yatak", "sentence_en": "I sleep in my bed.", "sentence_tr": "Yatağımda uyuyorum."},
    {"word": "beginning", "type": "noun", "meaning": "başlangıç", "sentence_en": "This is the beginning.", "sentence_tr": "Bu başlangıç."},
    {"word": "behavior", "type": "noun", "meaning": "davranış", "sentence_en": "His behavior is good.", "sentence_tr": "Davranışı iyi."},
    {"word": "belief", "type": "noun", "meaning": "inanç", "sentence_en": "I respect your belief.", "sentence_tr": "İnancına saygı duyuyorum."},
    {"word": "bird", "type": "noun", "meaning": "kuş", "sentence_en": "I see a bird.", "sentence_tr": "Bir kuş görüyorum."},
    {"word": "birth", "type": "noun", "meaning": "doğum", "sentence_en": "When is your birth date?", "sentence_tr": "Doğum tarihin ne?"},
    {"word": "blood", "type": "noun", "meaning": "kan", "sentence_en": "Blood is red.", "sentence_tr": "Kan kırmızı."},
    {"word": "body", "type": "noun", "meaning": "vücut", "sentence_en": "Take care of your body.", "sentence_tr": "Vücuduna dikkat et."},
    {"word": "book", "type": "noun", "meaning": "kitap", "sentence_en": "I read a book.", "sentence_tr": "Bir kitap okuyorum."},
    {"word": "boy", "type": "noun", "meaning": "erkek çocuk", "sentence_en": "The boy is playing.", "sentence_tr": "Erkek çocuk oynuyor."},
    {"word": "bread", "type": "noun", "meaning": "ekmek", "sentence_en": "I eat bread.", "sentence_tr": "Ekmek yiyorum."},
    {"word": "break", "type": "noun", "meaning": "mola", "sentence_en": "Let's take a break.", "sentence_tr": "Bir mola verelim."},
    {"word": "breakfast", "type": "noun", "meaning": "kahvaltı", "sentence_en": "I eat breakfast.", "sentence_tr": "Kahvaltı yiyorum."},
    {"word": "brother", "type": "noun", "meaning": "erkek kardeş", "sentence_en": "My brother is tall.", "sentence_tr": "Erkek kardeşim uzun."},
    {"word": "building", "type": "noun", "meaning": "bina", "sentence_en": "This is a tall building.", "sentence_tr": "Bu yüksek bir bina."},
    {"word": "business", "type": "noun", "meaning": "iş", "sentence_en": "I have a business.", "sentence_tr": "Bir işim var."},
    {"word": "car", "type": "noun", "meaning": "araba", "sentence_en": "I drive a car.", "sentence_tr": "Araba sürüyorum."},
    {"word": "card", "type": "noun", "meaning": "kart", "sentence_en": "I have a credit card.", "sentence_tr": "Bir kredi kartım var."},
    {"word": "care", "type": "noun", "meaning": "bakım", "sentence_en": "Take care of yourself.", "sentence_tr": "Kendine dikkat et."},
    {"word": "case", "type": "noun", "meaning": "durum", "sentence_en": "This is a special case.", "sentence_tr": "Bu özel bir durum."},
    {"word": "cause", "type": "noun", "meaning": "neden", "sentence_en": "What is the cause?", "sentence_tr": "Neden nedir?"},
    {"word": "center", "type": "noun", "meaning": "merkez", "sentence_en": "This is the center.", "sentence_tr": "Bu merkez."},
    {"word": "chair", "type": "noun", "meaning": "sandalye", "sentence_en": "Sit on the chair.", "sentence_tr": "Sandalyeye otur."},
    {"word": "change", "type": "noun", "meaning": "değişiklik", "sentence_en": "This is a big change.", "sentence_tr": "Bu büyük bir değişiklik."},
    {"word": "child", "type": "noun", "meaning": "çocuk", "sentence_en": "The child is happy.", "sentence_tr": "Çocuk mutlu."},
    {"word": "city", "type": "noun", "meaning": "şehir", "sentence_en": "I live in a big city.", "sentence_tr": "Büyük bir şehirde yaşıyorum."},
    {"word": "class", "type": "noun", "meaning": "sınıf", "sentence_en": "I go to class.", "sentence_tr": "Sınıfa gidiyorum."},
    {"word": "clothes", "type": "noun", "meaning": "kıyafet", "sentence_en": "I buy new clothes.", "sentence_tr": "Yeni kıyafet alıyorum."},
    {"word": "color", "type": "noun", "meaning": "renk", "sentence_en": "What color do you like?", "sentence_tr": "Hangi rengi seviyorsun?"},
    {"word": "company", "type": "noun", "meaning": "şirket", "sentence_en": "I work for a company.", "sentence_tr": "Bir şirket için çalışıyorum."},
    {"word": "computer", "type": "noun", "meaning": "bilgisayar", "sentence_en": "I use a computer.", "sentence_tr": "Bilgisayar kullanıyorum."},
    {"word": "condition", "type": "noun", "meaning": "durum", "sentence_en": "What is the condition?", "sentence_tr": "Durum nedir?"},
    {"word": "country", "type": "noun", "meaning": "ülke", "sentence_en": "I love my country.", "sentence_tr": "Ülkemi seviyorum."},
    {"word": "course", "type": "noun", "meaning": "kurs", "sentence_en": "I take a course.", "sentence_tr": "Bir kurs alıyorum."},
    {"word": "day", "type": "noun", "meaning": "gün", "sentence_en": "Today is a good day.", "sentence_tr": "Bugün iyi bir gün."},
    {"word": "death", "type": "noun", "meaning": "ölüm", "sentence_en": "Death is natural.", "sentence_tr": "Ölüm doğal."},
    {"word": "decision", "type": "noun", "meaning": "karar", "sentence_en": "This is my decision.", "sentence_tr": "Bu benim kararım."},
    {"word": "development", "type": "noun", "meaning": "gelişim", "sentence_en": "This shows development.", "sentence_tr": "Bu gelişim gösteriyor."},
    {"word": "difference", "type": "noun", "meaning": "fark", "sentence_en": "What is the difference?", "sentence_tr": "Fark nedir?"},
    {"word": "direction", "type": "noun", "meaning": "yön", "sentence_en": "Which direction?", "sentence_tr": "Hangi yön?"},
    {"word": "door", "type": "noun", "meaning": "kapı", "sentence_en": "Open the door.", "sentence_tr": "Kapıyı aç."},
    {"word": "earth", "type": "noun", "meaning": "dünya", "sentence_en": "We live on earth.", "sentence_tr": "Dünyada yaşıyoruz."},
    {"word": "education", "type": "noun", "meaning": "eğitim", "sentence_en": "Education is important.", "sentence_tr": "Eğitim önemli."},
    {"word": "effect", "type": "noun", "meaning": "etki", "sentence_en": "What is the effect?", "sentence_tr": "Etki nedir?"},
    {"word": "end", "type": "noun", "meaning": "son", "sentence_en": "This is the end.", "sentence_tr": "Bu son."},
    {"word": "energy", "type": "noun", "meaning": "enerji", "sentence_en": "I have energy.", "sentence_tr": "Enerjim var."},
    {"word": "example", "type": "noun", "meaning": "örnek", "sentence_en": "Give me an example.", "sentence_tr": "Bana bir örnek ver."},
    {"word": "experience", "type": "noun", "meaning": "deneyim", "sentence_en": "I have experience.", "sentence_tr": "Deneyimim var."},
    {"word": "eye", "type": "noun", "meaning": "göz", "sentence_en": "My eye hurts.", "sentence_tr": "Gözüm ağrıyor."},
    {"word": "face", "type": "noun", "meaning": "yüz", "sentence_en": "Wash your face.", "sentence_tr": "Yüzünü yıka."},
    {"word": "fact", "type": "noun", "meaning": "gerçek", "sentence_en": "This is a fact.", "sentence_tr": "Bu bir gerçek."},
    {"word": "family", "type": "noun", "meaning": "aile", "sentence_en": "I love my family.", "sentence_tr": "Ailemi seviyorum."},
    {"word": "father", "type": "noun", "meaning": "baba", "sentence_en": "My father is strong.", "sentence_tr": "Babam güçlü."},
    {"word": "food", "type": "noun", "meaning": "yemek", "sentence_en": "I like this food.", "sentence_tr": "Bu yemeği seviyorum."},
    {"word": "foot", "type": "noun", "meaning": "ayak", "sentence_en": "My foot hurts.", "sentence_tr": "Ayağım ağrıyor."},
    {"word": "friend", "type": "noun", "meaning": "arkadaş", "sentence_en": "He is my friend.", "sentence_tr": "O benim arkadaşım."},
    {"word": "game", "type": "noun", "meaning": "oyun", "sentence_en": "Let's play a game.", "sentence_tr": "Bir oyun oynayalım."},
    {"word": "girl", "type": "noun", "meaning": "kız", "sentence_en": "The girl is smart.", "sentence_tr": "Kız akıllı."},
    {"word": "government", "type": "noun", "meaning": "hükümet", "sentence_en": "The government helps people.", "sentence_tr": "Hükümet insanlara yardım eder."},
    {"word": "group", "type": "noun", "meaning": "grup", "sentence_en": "We are a group.", "sentence_tr": "Biz bir grubuz."},
    {"word": "hand", "type": "noun", "meaning": "el", "sentence_en": "Raise your hand.", "sentence_tr": "Elini kaldır."},
    {"word": "head", "type": "noun", "meaning": "baş", "sentence_en": "My head hurts.", "sentence_tr": "Başım ağrıyor."},
    {"word": "health", "type": "noun", "meaning": "sağlık", "sentence_en": "Health is important.", "sentence_tr": "Sağlık önemli."},
    {"word": "heart", "type": "noun", "meaning": "kalp", "sentence_en": "My heart beats fast.", "sentence_tr": "Kalbim hızlı atıyor."},
    {"word": "help", "type": "noun", "meaning": "yardım", "sentence_en": "I need help.", "sentence_tr": "Yardıma ihtiyacım var."},
    {"word": "home", "type": "noun", "meaning": "ev", "sentence_en": "I go home.", "sentence_tr": "Eve gidiyorum."},
    {"word": "hour", "type": "noun", "meaning": "saat", "sentence_en": "What time is it?", "sentence_tr": "Saat kaç?"},
    {"word": "house", "type": "noun", "meaning": "ev", "sentence_en": "I live in a house.", "sentence_tr": "Bir evde yaşıyorum."},
    {"word": "idea", "type": "noun", "meaning": "fikir", "sentence_en": "I have an idea.", "sentence_tr": "Bir fikrim var."},
    {"word": "information", "type": "noun", "meaning": "bilgi", "sentence_en": "I need information.", "sentence_tr": "Bilgiye ihtiyacım var."},
    {"word": "interest", "type": "noun", "meaning": "ilgi", "sentence_en": "I have interest in music.", "sentence_tr": "Müziğe ilgim var."},
    {"word": "job", "type": "noun", "meaning": "iş", "sentence_en": "I have a job.", "sentence_tr": "Bir işim var."},
    {"word": "key", "type": "noun", "meaning": "anahtar", "sentence_en": "Where is my key?", "sentence_tr": "Anahtarım nerede?"},
    {"word": "language", "type": "noun", "meaning": "dil", "sentence_en": "I speak a language.", "sentence_tr": "Bir dil konuşuyorum."},
    {"word": "law", "type": "noun", "meaning": "yasa", "sentence_en": "This is the law.", "sentence_tr": "Bu yasa."},
    {"word": "life", "type": "noun", "meaning": "hayat", "sentence_en": "Life is beautiful.", "sentence_tr": "Hayat güzel."},
    {"word": "light", "type": "noun", "meaning": "ışık", "sentence_en": "Turn on the light.", "sentence_tr": "Işığı aç."},
    {"word": "line", "type": "noun", "meaning": "çizgi", "sentence_en": "Draw a line.", "sentence_tr": "Bir çizgi çiz."},
    {"word": "love", "type": "noun", "meaning": "aşk", "sentence_en": "Love is powerful.", "sentence_tr": "Aşk güçlü."},
    {"word": "man", "type": "noun", "meaning": "adam", "sentence_en": "The man is tall.", "sentence_tr": "Adam uzun."},
    {"word": "money", "type": "noun", "meaning": "para", "sentence_en": "I need money.", "sentence_tr": "Paraya ihtiyacım var."},
    {"word": "month", "type": "noun", "meaning": "ay", "sentence_en": "What month is it?", "sentence_tr": "Hangi ay?"},
    {"word": "mother", "type": "noun", "meaning": "anne", "sentence_en": "My mother is kind.", "sentence_tr": "Annem nazik."},
    {"word": "music", "type": "noun", "meaning": "müzik", "sentence_en": "I love music.", "sentence_tr": "Müziği seviyorum."},
    {"word": "name", "type": "noun", "meaning": "isim", "sentence_en": "What is your name?", "sentence_tr": "Adın ne?"},
    {"word": "night", "type": "noun", "meaning": "gece", "sentence_en": "Good night.", "sentence_tr": "İyi geceler."},
    {"word": "number", "type": "noun", "meaning": "numara", "sentence_en": "What is your number?", "sentence_tr": "Numaran nedir?"},
    {"word": "office", "type": "noun", "meaning": "ofis", "sentence_en": "I work in an office.", "sentence_tr": "Bir ofiste çalışıyorum."},
    {"word": "order", "type": "noun", "meaning": "sipariş", "sentence_en": "I place an order.", "sentence_tr": "Bir sipariş veriyorum."},
    {"word": "paper", "type": "noun", "meaning": "kağıt", "sentence_en": "I write on paper.", "sentence_tr": "Kağıda yazıyorum."},
    {"word": "people", "type": "noun", "meaning": "insanlar", "sentence_en": "Many people came.", "sentence_tr": "Çok insan geldi."},
    {"word": "person", "type": "noun", "meaning": "kişi", "sentence_en": "He is a good person.", "sentence_tr": "O iyi bir kişi."},
    {"word": "phone", "type": "noun", "meaning": "telefon", "sentence_en": "I use my phone.", "sentence_tr": "Telefonumu kullanıyorum."},
    {"word": "picture", "type": "noun", "meaning": "resim", "sentence_en": "I take a picture.", "sentence_tr": "Bir resim çekiyorum."},
    {"word": "place", "type": "noun", "meaning": "yer", "sentence_en": "This is a nice place.", "sentence_tr": "Bu güzel bir yer."},
    {"word": "plan", "type": "noun", "meaning": "plan", "sentence_en": "I have a plan.", "sentence_tr": "Bir planım var."},
    {"word": "problem", "type": "noun", "meaning": "problem", "sentence_en": "I have a problem.", "sentence_tr": "Bir problemim var."},
    {"word": "question", "type": "noun", "meaning": "soru", "sentence_en": "I have a question.", "sentence_tr": "Bir sorum var."},
    {"word": "reason", "type": "noun", "meaning": "neden", "sentence_en": "What is the reason?", "sentence_tr": "Neden nedir?"},
    {"word": "result", "type": "noun", "meaning": "sonuç", "sentence_en": "What is the result?", "sentence_tr": "Sonuç nedir?"},
    {"word": "room", "type": "noun", "meaning": "oda", "sentence_en": "I clean my room.", "sentence_tr": "Odamı temizliyorum."},
    {"word": "school", "type": "noun", "meaning": "okul", "sentence_en": "I go to school.", "sentence_tr": "Okula gidiyorum."},
    {"word": "sister", "type": "noun", "meaning": "kız kardeş", "sentence_en": "My sister is young.", "sentence_tr": "Kız kardeşim genç."},
    {"word": "society", "type": "noun", "meaning": "toplum", "sentence_en": "We live in society.", "sentence_tr": "Toplumda yaşıyoruz."},
    {"word": "story", "type": "noun", "meaning": "hikaye", "sentence_en": "I tell a story.", "sentence_tr": "Bir hikaye anlatıyorum."},
    {"word": "student", "type": "noun", "meaning": "öğrenci", "sentence_en": "I am a student.", "sentence_tr": "Ben bir öğrenciyim."},
    {"word": "study", "type": "noun", "meaning": "çalışma", "sentence_en": "I do my study.", "sentence_tr": "Çalışmamı yapıyorum."},
    {"word": "system", "type": "noun", "meaning": "sistem", "sentence_en": "This is a good system.", "sentence_tr": "Bu iyi bir sistem."},
    {"word": "table", "type": "noun", "meaning": "masa", "sentence_en": "I sit at the table.", "sentence_tr": "Masaya oturuyorum."},
    {"word": "teacher", "type": "noun", "meaning": "öğretmen", "sentence_en": "My teacher is kind.", "sentence_tr": "Öğretmenim nazik."},
    {"word": "team", "type": "noun", "meaning": "takım", "sentence_en": "We are a team.", "sentence_tr": "Biz bir takımız."},
    {"word": "thing", "type": "noun", "meaning": "şey", "sentence_en": "What is this thing?", "sentence_tr": "Bu şey nedir?"},
    {"word": "time", "type": "noun", "meaning": "zaman", "sentence_en": "Time is precious.", "sentence_tr": "Zaman değerli."},
    {"word": "water", "type": "noun", "meaning": "su", "sentence_en": "I drink water.", "sentence_tr": "Su içiyorum."},
    {"word": "way", "type": "noun", "meaning": "yol", "sentence_en": "Which way?", "sentence_tr": "Hangi yol?"},
    {"word": "week", "type": "noun", "meaning": "hafta", "sentence_en": "I work this week.", "sentence_tr": "Bu hafta çalışıyorum."},
    {"word": "woman", "type": "noun", "meaning": "kadın", "sentence_en": "The woman is beautiful.", "sentence_tr": "Kadın güzel."},
    {"word": "word", "type": "noun", "meaning": "kelime", "sentence_en": "I learn new words.", "sentence_tr": "Yeni kelimeler öğreniyorum."},
    {"word": "work", "type": "noun", "meaning": "iş", "sentence_en": "I do my work.", "sentence_tr": "İşimi yapıyorum."},
    {"word": "world", "type": "noun", "meaning": "dünya", "sentence_en": "I love the world.", "sentence_tr": "Dünyayı seviyorum."},
    {"word": "year", "type": "noun", "meaning": "yıl", "sentence_en": "Happy new year.", "sentence_tr": "Mutlu yıllar."}
]

# Tüm kelimeleri birleştir
all_words = existing_words + additional_words

# Dosyaya yaz
with open('public/words.json', 'w', encoding='utf-8') as f:
    json.dump(all_words, f, ensure_ascii=False, indent=2)

print(f"Toplam {len(all_words)} kelime oluşturuldu!")
print("Dosya: public/words.json") 