name: Build Android App Bundle (AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aab:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Create keystore
      run: |
        keytool -genkeypair -v -keystore daily-words-keystore.jks -alias dailywords -keyalg RSA -keysize 2048 -validity 10000 -storepass dailywords123 -keypass dailywords123 -dname "CN=Burak Avci, OU=Development, O=Daily Words, L=Istanbul, ST=Istanbul, C=TR"
        
    - name: Initialize Bubblewrap project
      run: |
        bubblewrap init --manifest https://daily-words-apk.vercel.app/manifest.webmanifest --directory ./bubblewrap
        
    - name: Build AAB with keystore
      run: |
        cd bubblewrap
        bubblewrap build --target android
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bubblewrap/app-release.aab 