name: Build Android App Bundle (AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aab:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Initialize Bubblewrap project
      run: |
        bubblewrap init --manifest https://daily-words-apk-git-main-burakavcis-projects.vercel.app/manifest.webmanifest
      env:
        BUBBLEWRAP_KEYSTORE_PATH: ${{ secrets.BUBBLEWRAP_KEYSTORE_PATH }}
        BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.BUBBLEWRAP_KEYSTORE_PASSWORD }}
        BUBBLEWRAP_KEY_ALIAS: ${{ secrets.BUBBLEWRAP_KEY_ALIAS }}
        BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.BUBBLEWRAP_KEY_PASSWORD }}
        
    - name: Build AAB
      run: |
        bubblewrap build --target android
      env:
        BUBBLEWRAP_KEYSTORE_PATH: ${{ secrets.BUBBLEWRAP_KEYSTORE_PATH }}
        BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.BUBBLEWRAP_KEYSTORE_PASSWORD }}
        BUBBLEWRAP_KEY_ALIAS: ${{ secrets.BUBBLEWRAP_KEY_ALIAS }}
        BUBBLEWRAP_KEY_PASSWORD: ${{ secrets.BUBBLEWRAP_KEY_PASSWORD }}
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app-release.aab 