name: Build Android App Bundle (AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aab:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Test manifest URL
      run: |
        curl -I https://daily-words-apk-git-main-burakavcis-projects.vercel.app/manifest.webmanifest
        
    - name: Initialize Bubblewrap project (without keystore)
      run: |
        bubblewrap init --manifest https://daily-words-apk-git-main-burakavcis-projects.vercel.app/manifest.webmanifest --directory ./bubblewrap --skipPwaValidation
        
    - name: Build AAB (debug version)
      run: |
        cd bubblewrap
        bubblewrap build --target android --skipPwaValidation
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bubblewrap/app-debug.aab 